### ISSUE TITLE
Custom Attributes Documentation

### ISSUE THREAD

**Issue by timReynolds** [nunit/docs#110]
I was looking at rewriting an add-on from v2 but the documentation around [Customer Attributes](https://github.com/nunit/docs/wiki/Custom-Attributes) has yet to be completed. Whats the best source to understand how to write a custom attribute? Are there any examples or is it just dive into the source code?

**Comment by CharliePoole** [comment]
I'm afraid that's it. You can look at how NUnit's own attrributes are implemented, since they use the same interfaces as custom attributes would use. If you tell me what kind of v2 addin you are trying to rewrite I can give you some pointers of where to look.

BTW, we already have issue #40 about writing this documentation, so I'm just treating this one as a question.

**Comment by timReynolds** [comment]
I want to create a retry attribute based on this v2 add-on; 
https://github.com/slvnperron/NUnit-retry

We have the same use case of a large regression suite that has many dependencies causing transient failures. In many cases we've rewritten the tests to improve better reliability but some still require this type of functionality.  

I'll also have to get this to work with the specFlow generator in someway but one step at a time. Due to this however I thought it might be nicer to implement it using a similar approach to the Parallelizable attribute that can be set in AssemblyInfo.cs.

**Comment by CharliePoole** [comment]
The obvious place to start would be with NUnit's own RetryAttribute, generalizing it to require a specified number of passing test cases rather than just one.

Specifying a default value for this in AssemblyInfo.cs and having NUnit apply it everywhere would require NUnit to be modified. NUnit understands a few things that apply to individual tests, like parallizability and the default timeout value, but there's no general concept of retrying the test some number of times without an attribute on the test.

**Comment by timReynolds** [comment]
Interesting, I didn't know NUnit had the RetryAttribute. As I know the test I want to be retried maybe I'm best to get the specFlow generator to support retry tags, this plugin looks like a better place to start; 
https://github.com/arrty/specflow-retry

**Comment by CharliePoole** [comment]
However, the semantics of the NUnit RetryAttribute doesn't match that of the V2 attribute you linked to.
