### ISSUE TITLE
NUnitLite ignores --params

### ISSUE THREAD

**Issue by KWodarczyk** [nunit/docs#124]
I am trying to pass in parameters to a test method but it if  i tired to read them in the test the list is empty e.g TestContextParameters.Names.Count results in 0

I am passing the arguments to the AutoRun as  follows
```

 string[] args = new[]
                               {
                                   "--result:TestOuput_.xml",
                                   "--test=MyTestMethod",
                                   "--params:p=myvalue,c=myvalue2"
                               };

new AutoRun(MyTestAssembly).Execute(parameters.args);
```

In my test method i do

 ```
TestParameters p = TestContext.Parameters.n;
            List<string> parNames = new List<string>();
            foreach (string name in p.Names)
            {
                parNames.Add(name);
            }            
            Assert.IsNotNull(parNames, "parameter are null");
            Assert.IsTrue(parNames.Count > 0, "parameters count is zero");
```

and the last assert fails, however if i run the same method in the console i works fine

**Comment by CharliePoole** [comment]
NUnitLite does not support the `--params` option at all. It's actually an error that the argument is being accepted without error.

At the time we implemented this feature in the console, it was sharing some code with NUnitLite. The new option was placed in CommandLineOptions.cs, which was actually designed to hold options that are shared between the two programs. Subsequently, we split the NUnit framework and console/engine into separate repositories. NUnitLite, of course, is part of the framework and the file that validates options was replicated there, including the option that it actually doesn't use.

Thanks for highlighting this problem. I have created issue nunit/nunit#1829 so that we can fix it. I also created issue #125 in this repository so we will actually document the nunitlite command-line.

Note that you created this issue in the docs repository, which is for documentation errors. In this case, it's easy to answer you here rather than moving it to the correct repo, but it's preferred that you use the nunit repo for framework/nunitlite problems.
