### ISSUE TITLE
NUnit Console ignores config if result specified on mono

### ISSUE THREAD

**Issue by kataik** [nunit/docs#126]
If I execute the following command on **mono**:
`mono ./tools/NUnitConsoleRunner/nunit3-console.exe ./src/T_GitLabCi/T_GitLabCi.sln --result=TestResult.xml;format=nunit2 --work=./src/T_GitLabCi/test --config=Release`

I get the following error (for each test assembly):

> Invalid : /builds/kataik/gitlab_test/src/T_GitLabCi/TestLibrary.Tests/bin/Debug/TestLibrary.Tests.dll
> File not found: /builds/kataik/gitlab_test/src/T_GitLabCi/TestLibrary.Tests/bin/Debug/TestLibrary.Tests.dll

If I execute the same in **Windows**, it gets executed properly. Similarly if I do not specify the _--result_ argument, it works properly on **mono** as well. I don't know how an output argument has effect on an input. Strange. (To have _sonar_ scanner work properly, I need the output format supported by _nunit2_.)

**Version**: NUnit Console Runner 3.5.0
**OS**: Linux 4.4.0.38
**CLR**: 4.0.30319.42000

**Comment by rprouse** [comment]
I believe it is the semicolon in the result that is causing you problems since it indicates the end of the current command so the remaining --work and --config are not parsed. You need to quote the ;

See #1571 for information.

I am closing this as a duplicate. Please comment and reopen if my diagnosis is incorrect.

**Comment by kataik** [comment]
@rprouse You are correct sir, thank you.
