### ISSUE TITLE
How am I supposed to install v 3.5 console runner with v3.5 framework with no installer?

### ISSUE THREAD

**Issue by agray** [nunit/docs#128]
I uninstalled v3.4.1, then installed nunit-console.msi and as there is no installer anymore for the framework I copied the .net 4.5 files from the framework zip to C:\Program Files (x86)\NUnit.org but I get this error

    System.IO.FileLoadException: Could not load file or assembly 'nunit.framework, Version=3.5.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
    File name: 'nunit.framework, Version=3.5.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' ---> System.IO.FileLoadException: Could not load file or assembly 'nunit.framework' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
    File name: 'nunit.framework'

Are there any instructions on how to upgrade?

**Comment by CharliePoole** [comment]
If you prefer to install the framework centrally, unzip it in s convenient location. Don't mix it into any of the directories that hold the engine or console runner. I recommend you use a separate directory for each framework version you install rather than overwrite the older version.

Reference the assembly from your test project setting copy local to true. 

This is exactly how the previous release worked as well.

**Comment by agray** [comment]
nunit nuget package is referenced in my test project and nunit.framework has copy local set to true.  Yet I am still getting the error that it can't load the framework....  Please advise.

**Comment by CharliePoole** [comment]
What are the  contents of the output directory that contains the test assembly you are loading?

**Comment by agray** [comment]
bin\Release directory in Jenkins workspace has:

    appium-dotnet-driver.dll
    appium-dotnet-driver.xml
    Castle.Core.dll
    Castle.Core.dll.VisualState.xml
    Castle.Core.xml
    Newtonsoft.Json.dll
    Newtonsoft.Json.dll.VisualState.xml
    Newtonsoft.Json.xml
    nunit.framework.dll
    nunit.framework.dll.VisualState.xml
    RestSharp.dll
    RestSharp.dll.VisualState.xml
    RestSharp.xml
    Saucery3.dll
    Saucery3Tester.dll
    Saucery3Tester.dll.config
    Saucery3Tester.pdb
    Shouldly.dll
    Shouldly.dll.VisualState.xml
    WebDriver.dll
    WebDriver.dll.VisualState.xml
    WebDriver.Support.dll
    WebDriver.Support.dll.VisualState.xml
    WebDriver.Support.xml
    WebDriver.xml

**Comment by CharliePoole** [comment]
The message indicates that one of your files expects a different version of the framework than the one you are providing - either older or newer. In addition The presence of files with the `.VisualState.xml` extension is suspicious, since it they are created by the NUnit V2 Gui.

You should first examine the copy of nunit.framework in your output directory to see what version it is. You can determine that by viewing the properties of the file. If it's 3.5, then the errors refer to an assembly that is referencing an older version. If it's an older version, then the assemblies that are __not__ causing an error are the ones with the problem.

If you want further help with this, please provide an example that uses NUnit alone to run tests, without 3rd party additions, and ask on the discussion list or as an nunit issue rather than in the docs repository.

**Comment by agray** [comment]
Thanks Charlie,  You were correct.  There was an old version being pulled in.  Resolving this resolved the issue.
