### ISSUE TITLE
Update Breaking Changes with v3.5 distribution changes

### ISSUE THREAD

**Issue by dfev77** [nunit/docs#130]
Hi,

I was trying to use nunit 3.5.0 and noticed that nunit3-console.exe was not present in the downloaded zip package (https://github.com/nunit/nunit/releases/tag/3.5), there is just the nunitlite-runner.exe. For the console you now have to download another package.
The thing is, this is a breaking change (for our scripts) which is not mentioned is the docs.

Will the future versions add back the nunit3-console.exe runner or only the lite version will be available from now one?
Why the lite runner is included but nunit3-console was moved to another package?

**Comment by ChrisMaddock** [comment]
The console was separated from the framework, to allow the two components to be developed separately.  In the future, the releases of console and framework may not even happen at the same time, and the version numbers will no longer be in sync. 

The console release can now be found at the link below, they'll be distributed separately from now.

**Comment by ChrisMaddock** [comment]
The console was separated from the framework to allow the two components to be developed separately. In the future, the releases of console and framework may not even happen at the same time, and the version numbers will no longer be in sync. You're right that this should be on the 'breaking changes' page however, I'll re-title your issue to reflect that needs to be done.

The console release can now be found at the link below, they'll be distributed separately from now on.
https://github.com/nunit/nunit-console/releases

> Why the lite runner is included but nunit3-console was moved to another package?

The NUnitLite runner is just a small lightweight wrapper that integrates directly with the framework to run tests. The console is a much larger runner, with significantly more functionality.

Out of interest, is there a particular reason why you have scripts to download the zips, rather than using a package manager such as NuGet?

**Comment by CharliePoole** [comment]
This should probably be in breaking changes along with a few other things that have come up. We'll have to reorganize the page so it shows breaking changes by release.

**Comment by dfev77** [comment]
We have an automated build process based on gradle which has to be able to build projects referencing different NUnit version.
I would be interested in the differences between lite and standard console runner to understand if we can go for the lite one or not. For now the only information I have found on the lite version is this page https://github.com/nunit/docs/wiki/NUnitLite-Unification-Spec but I have the feeling it it not up to date.

Should I enter another issue for detailing the lite vs standard console runner?

**Comment by rprouse** [comment]
@CharliePoole what are your thoughts on the `nunitlite-runner.exe` that is included in the ZIP? I have always considered it as part of our unit tests and only intended to run our tests. I didn't envision people downloading the ZIP and using it. I am assuming that you thought the same since it isn't included in any other distribution?

If so, should we make that clear in the documentation?

**Comment by CharliePoole** [comment]
I thought of it as a way to use nunitlite without making your tests into an executable. Maybe that should be added to the docs.

**Comment by SeanKilleen** [comment]
Closed per discussion on #588.
