### ISSUE TITLE
Add Project Editor documentation

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#144]
Although we have often told users that they should use the project editor, they don't find any documentation for it in the current wiki. We should remedy that.

The project editor was distributed with NUnit V2 but has no dependencies on any version of NUnit. By design, it doesn't use the NUnit code to read or write the file format, which remains unchanged in the newer versions of NUnit. We should make this a separate section of the docs, albeit a small one, and convert the old documentation to the wiki.

**Comment by ChrisMaddock** [comment]
I did this a few months ago, Charlie. 😄 
https://github.com/nunit/docs/wiki/Project-Editor

Is it missing from an index page somewhere?

**Comment by CharliePoole** [comment]
Oddly, it has my name on it. Did I merge it for you?

The indexes look OK. I created this without checking because I didn't remember we had done it.

**Comment by ChrisMaddock** [comment]
I thought the same! Looks like you renamed it - which appears to have lost the wiki history.

**Comment by rprouse** [comment]
On a related note, should we move the project editor code into its own repo and release it on its own?

**Comment by ChrisMaddock** [comment]
We made a start on that as well, a few months back, when I did the docs. We did one 'as-is' release pushed to GitHub, and were then going to do 1.0 once a few critical issues had been fixed. There's only the one left, but Winforms gets me down. :-p Perhaps someone should possibly fix that, and do a 'proper' 1.0, maybe add it to the website and such.

Just had a look at the download count - there's been 24 downloads since May. Of course, it's had very limited visibility, only being released in the repo, but it's not so inspiring to put a lot more effort into it!

https://github.com/nunit/nunit-project-editor

**Comment by rprouse** [comment]
Wow, 24 downloads. I think the SilverLight package got more than that 😆

**Comment by CharliePoole** [comment]
@rprouse It has been a separate repo for a while. The older version still exists as part of the NUnitV2 repo, which is probably what led you to think it was still bundled. We did release 0.9, which is identical to the version that was part of 2.6.4.

As @ChrisMaddock points out, what is lacking is any visibility beyond the repo. Putting it into the docs is a good start and they should probably point out where to download it. I should add it to the downloads page as well. It will eventually be bundled with the new gui, where a menu option will invoke it just like in V2.

Right now, it is building toward milestone 0.9.1, which was to be the first release done completely on GitHub. In retrospect, the choice of a version number seems odd. There's one high-pri bug remaining to fix toward that release and five others, which would presumably be fixed for a 1.0 release.

This is one of those GUI things I haven't managed to work on for a while. One of these days, I'd like to fix that. :smile:
