### ISSUE TITLE
Enable collaboration on wiki's

### ISSUE THREAD

**Issue by SamJongenelen** [nunit/docs#147]
Hey guys,

Given the past few days I've been implementing NUnit goodness, I've discovered some features that aren't well documented yet (.runsettings NUnit 3.x parameters). I'd like to contribute my findings into the docs.wiki, but I've been struggling with submitting the changes I made, in it's current state of configuration.

tl;dr; It's too hard submit wiki updates :)

I can clone the _[docs.wiki](https://github.com/nunit/docs/wiki)_ git, but, of course, cannot submit changes. 
The repo https://github.com/nunit/docs/ does not contain the wiki directory, so i cannot make changes in a fork of this repo.
Is there any way you guys can change the system? Perhaps the following site makes more sense to you then it does to me.. (I'm fairly new with Git)
http://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html

**Comment by CharliePoole** [comment]
Yes, that's a weakness of GitHub wikis. We have not gone to the trouble described in the article you point to, although I'm familiar with the approach. In general, we just give people write access to the wiki.

I'll invite you to our Contributors Team, which - once you accept - gives you the ability to edit pages on the wiki directly or to branch it and create PRs.

For super-simple changes like spelling corrections, you should just edit the wiki.

For larger changes, create an issue here, edit the page and then post a comment asking for the change to be reviewed. Your change will be live immediately, but we can back it out or ask for changes if we don't like it. :smile: 

New pages or menu changes are problematic. New pages end up in the root of our directory structure and any editing of the menu affects the top-level menu, which is probably not what you wanted.

So, new pages or for changes to the menus you have to clone the wiki. The process is that you clone it locally, create a feature branch to work on, push that branch and submit a PR. Your change is of course in our wiki repo already, but not in the master branch until we merge it.

As an alternative process for more complex changes - you can ask somebody to create a page or pages in the proper directory and then edit them. You can also create new pages yourself (in the root) and ask somebody to move it to the right place afterwards.

It's definitely more complex than it has to be, but it's somewhat out of our hands.

**Comment by SamJongenelen** [comment]
Thank you for your extended comment. I will create a review.

**Comment by ChrisMaddock** [comment]
@CharliePoole @SamJongenelen - I'd love to see us have something that permits PRs - making contributions easier is always a plus, and doc contributions can also make great first-PR issues. Theoretically, would you be averse to us implementing something such as the above?

I remember we talked about this when the docs first moved into this wiki, and I believe we decided to leave it a while, and see how it goes. Perhaps it's time to restart that discussion? 😄

**Comment by CharliePoole** [comment]
@ChrisMaddock I reopened the issue so we can treat this issue more broadly. This was one of the issues I hoped that the newly defined (or getting defined) Core Team would deal with. (I have a whole backlist of issues for that group once it's finished getting formed.)

It's an issue for that governing group, in my mind, because it is at least potentially something we would require of all projects that we accept into the NUnit organization. We might want them to maintain their documentation in a certain way, just as we might ask them to use certain coding standards.

There are currently three different options on the table for maintaining docs, at least in my mind:

1. Keeping them on the existing docs wiki. That's kind of the default, which you are addressing.

2. Going back to individual wikis and keeping only landing pages for each one in the docs wiki. That's where we started, of course, but it's still a possibility.

3. Using a github.io site to maintain the docs. That's a direction I'm interested in.

So, I'd say that whether we make the specific change that is talked about in the article or not depends on how much work it would be and how long it will take before we decide the "ultimate" location of the docs.

Up to now, it has been pretty easy to just give people write access to the wiki and it hasn't caused any problems. In fact, I know that some of the folks who work in the docs are not programmers and wouldn't find creating a PR for a change to be as easy as all that.

The issue of the web site is one that's in my hands and that I have not been giving a big priority to. It's just too easy to keep paying the $3.95 per month the site costs while focusing on other things. I have to figure out how to disentangle nunit.com and nunitsoftware.com from nunit.org before the latter can go anywhere else. I'm open to suggestions for any kind of interim solutions that don't waste too many resources.

**Comment by ChrisMaddock** [comment]
Glad this was still on an 'agenda', happy to come back to this is a few weeks time if that makes more sense. 😊

I'd love to see us move towards 3 - I've always thought before that I've been in a minority on that front, however! I'd like to think GitHubs web interface for editing files in-place would make submitting doc changes non-technical 'enough' to rival the wiki - I quite often use that for minor corrections for other projects.

I think there's also an option 4, which may be a simpler interim measure - what Sam suggested, and we've discussed before - of setting up the main git repo here to mirror the wiki repo, and (ab)using some CI hook to keep the two in sync. That looks like it would allow us to have both editing options, if being a little messy.

Shall we mark this as blocked, until the website/core-team plans are more stable?

**Comment by BKSpurgeon** [comment]
hello i'm just learning Nunit - and i figure i may as well write a dummy proof guide, seeing i'm going through the process. is there a place where there is documentation on the Nunit methods available? all i know is assert.That() but i'm sure there is more powerful things that can be done? pls LMK. rgds, Ben

**Comment by CharliePoole** [comment]
Strangely, you're in the right place... assuming you are reading this on GitHub. Look at the top of the page and click on Wikik. :smile:

**Comment by BKSpurgeon** [comment]
Hello Charlie thanks for your response: I was expecting documentation like this: http://www.rubydoc.info/gems/cancancan/1.15.0/CanCan/Ability - example for the cancancan gem. is there a similar type of thing for nunit? rgds, Ben

**Comment by CharliePoole** [comment]
The best starting point is to read Getting Started in the wiki. From there, look at the main menu headings, like Writing Tests, Running Tests, etc. To use NUnit you need to know about Assertions, Attrbiutes and the particular runner you choose to use.
