### ISSUE TITLE
Retry(int count) is not triggered on Assertion failure in TearDown

### ISSUE THREAD

**Issue by andrewlaser** [nunit/docs#149]
The code below results in failed test case "Test", but Retry is not triggered as expected.

Reason, why I'm doing so:
I've got multiple soft assertions in one UI test case. IsTestCasePassed value is set "false" if at least one assertion fails.

    [TestFixture]
    public class MyTestCases : TestBase
    {
        [Test, Retry(2)]
        public void Test()
        {
            IsTestCasePassed = false;
        }
    }

    [TestFixture]
    public class TestBase
    {
        public bool IsTestCasePassed = true;
        [TearDown]
        public void TestFixtureTearDown()
        {
            if (!IsTestCasePassed)
            {
                Assert.Fail();
            }
        }
    }

**Comment by ChrisMaddock** [comment]
I don't believe it's permitted to use `Assert.Fail()` in a tear down. You'll be able to confirm this from your tests results, I believe when you run this code, you'll see an Exception about using `Assert.Fail()`, rather than an AssertionFailure? This means your test will error, rather than fail, which means the Retry attribute will not be activated.

It doesn't seem to be documented that `Assert.Fail()` can't be used in TearDown, but I have a memory of that being the case. If my memory's correct, that should probably be documented!

As an improved way of implementing this, fully fledged [Multiple Assertion](https://github.com/nunit/nunit/issues/391) functionality has been implemented by @CharliePoole, and should be coming in 3.6, due January. This would be the way to go for tests like these. 😄

**Comment by ChrisMaddock** [comment]
I tried this out. I think I'm correct, although the error message could perhaps be more helpful! 😄 

This is with an `Assert.Fail()` in a `[Test]`:

![image](https://cloud.githubusercontent.com/assets/4837132/21223259/394c1754-c2be-11e6-9153-68cf3da55944.png)

And this in the `[TearDown]`:

![image](https://cloud.githubusercontent.com/assets/4837132/21223247/2b7de03a-c2be-11e6-9911-990c38fc909b.png)

**Comment by CharliePoole** [comment]
As @ChrisMaddock correctly remembers, assertions have never been allowed in a TearDown. That's because TearDown is called in a finally clause and an exception may already have been thrown. Even an Assert.Pass will cause an error.

TearDown is for cleanup only. We have a request for a common PostTest step, which would allow assertions.

**Comment by andrewlaser** [comment]
Thanks for explanations.
Created an Action Attribute with AfterTest throwing Assert.Fail() BEFORE TearDown.

**Comment by andrewlaser** [comment]
Maybe you could answer, how can I access Retry counter?

**Comment by CharliePoole** [comment]
You can't but I think it's a good idea. For now just count the calls yourself.

**Comment by FestTestQA** [comment]
> 
> 
> You can't but I think it's a good idea. For now just count the calls yourself.

Was this ever implemented?

If so, where can i get the retryCount?

**Comment by CharliePoole** [comment]
@FestTestQA This documentation issue really never asked for anything to be implemented and was closed without changing the docs. To get something implemented in code, it's best to file an issue on the project that creates the code rather than the docs project.

A quick search in the nunit framework repo shows 15 open and 32 closed issues that mention retry: https://github.com/nunit/nunit/issues?q=is%3Aissue+retry+is%3Aclosed That would be a good starting point.

**Comment by FestTestQA** [comment]
gotcha thanks charlie.
