### ISSUE TITLE
Theory without parameters

### ISSUE THREAD

**Issue by seraphim207** [nunit/docs#162]
I have code base working with NUnit 2 that uses [Theory] instead [Test] in most cases as commonly boolean/enum variables added as a parameters to support multiple test cases. After moving to NUnit 3 I realized (only after certain amount of time) that theory tests without parameters are just ignored and not executed as it was in NUnit 2. They are just ignored and not shown as ignored in test window of VS. 

I vote for therories without parameters to be considere as usual tests. Or [Test] should provide same auto value filling for boolean/enums as [Theory] does. This is very convenient to mark tests with single attribute and don't fear that some test would just dissapear from invocation list after removing parameter.

**Comment by CharliePoole** [comment]
Please add a test case so we can be sure we understand the issue.

**Comment by seraphim207** [comment]
`        [Theory]
        public void ImInvoked(Boolean someBooleanParam)
        { }

        [Test]
        public void ImInvoked()
        { }

        [Theory]
        public void ImSkipped() // not visible for test adapter of NUnit 3, but was visible in NUnit 2
        { }
`

**Comment by CharliePoole** [comment]
This is how it's.intended to work, with the exception that I think you should get some kind of error in the last example. You OTOH, would prefer it to work - as I understand it - as if the attribute were [Test].

In NUnit, a Theory is a set of test cases with a special interpretation of the results, different from that of a test. It must always have parameters. It has further characteristics in the implementation, beyond that definition:
 * Use of Datapoints to supply data
 * Generation of boolean and enum arguments when not supplied

You appear to be using Theory for one of it's secondary characteristics - the last one - rather than because you actually have a theory to be validated. Unfortunately, that's outside of the intent of the feature.

We could consider adding automatic generation of args to parameterized tests. Your examples don't include a parameterized test (a non-Theory, that is) without args provided, which would look like this:

```C#
[Test]
public void MyMethod(bool myarg)
{
}
```

What do others thing about this? It's currently an error, but we could check for args that we can generate and allow it.

**Comment by CharliePoole** [comment]
Since this is not really a documentation issue, I'm moving it to the  nunit repository.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit #2016](https://github.com/nunit/nunit/issues/2016) via [**ZenHub**](https://www.zenhub.com/)
