### ISSUE TITLE
Explicit test display Inconclusive: Test not run, instead string supplied in argument

### ISSUE THREAD

**Issue by Cvallee1** [nunit/docs#165]
I have a test that uses the explicit attribute for which I have supplied a string argument to document the reason for which it is skipped.

However in the GUI, I still see only : Inconclusive test not run, instead of the expected string.

I am using NUnit 3.6.0.0 in VS2015 with Resharper 2016.3

Here is a snippet:

        [TestCase((ushort) 0, "4", true)]
        [TestCase((ushort) 65532, "4", true)]
        [TestCase((ushort) 0, "0", false)]
        [TestCase((ushort) 0, "1", true)]
        [TestCase((ushort) 0, "7", true)]
        [TestCase((ushort) 0, "0,1", false)]
        [TestCase((ushort) 0, "1,2,3", true)]
        [TestCase((ushort) 0, "1,2,3,4", true)]
        [TestCase((ushort) 0, "1,2,10", false)]
        [TestCase((ushort) 0, "8,9", false)]
        [TestCase((ushort) 0, "1,2,11", false)]
        [Explicit("Test too slow")]

        public void test(ushort aShort, string testString, bool aBool)

**Comment by CharliePoole** [comment]
This is the repository for reporting documentation errors. In order to evaluate your issue and move it to the correct repo, I need some more information.

When you refer to the "GUI" do you mean the NUnit Gui under development (current version 0.3)? Or is it the Visual Studio test explorer display? Or is it some report that is produced by Resharper?

All the NUnit framework and engine do is report that the test was skipped as explicit. It's up to the runner you are using to decide how to display that. So, in the end, this is probably an issue for the NUnit Gui or the NUnit Visual Studio adapter or Resharper. 

Please let us know where you are seeing the bad report. Another good way to clarify this would be for you to run your tests under the NUnit console runner and see what is displayed there. You could also examine the XML output from the test run, but that's only available using certain runners.

**Comment by Cvallee1** [comment]
Hi Charlie thank you for your prompt response I have run the test with the NUnit console runner and it does appear to function as excpected and I get the following result in xml:
<properties>
     <property name="_SKIPREASON" value="Test too slow" />
</properties>

And the same message attached to all my testcases.

Therefore, it appears to be an issue with the Resharper GUI, I will get in touch with them.
Thank you for the help.

**Comment by Cvallee1** [comment]
I found the bug reported here: https://youtrack.jetbrains.com/issue/RSRP-459041
