### ISSUE TITLE
TestCaseSource example generates error

### ISSUE THREAD

**Issue by fajohn** [nunit/docs#184]
When running the code as is get

"Test method has non-void return type, but no result is expected." for each of the test data entries

**Comment by immeraufdemhund** [comment]
Which one? I've looked at both [TestCaseSource ](https://github.com/nunit/docs/wiki/TestCaseSource-Attribute) and [TestCaseData ](https://github.com/nunit/docs/wiki/TestCaseData) (which also has an example) and they appear correct to me.

**Comment by CharliePoole** [comment]
When reporting an error in the docs, please include a link to the page in which you find the error along with enough info to figure out where on the page it is, if there is any ambiguity.

**Comment by fajohn** [comment]
It is the TestCaseSource link above. I tried running it through SharpDevelop after a NuGet of version 3.6.1.

**Comment by CharliePoole** [comment]
There are actually three examples on that page. However, since you mention SharpDevelop, that may be a hint of where the problem lies. If you are using a runner that's part of SharpDevelop, it may not support NUnit 3.6.1 or even NUnit 3 at all.

A quick search for "SharpDevelop NUnit 3" turned up a number of relevant posts, such as this one: https://github.com/icsharpcode/SharpDevelop/issues/781

I'll wait for you to confirm that it's a compatibility issue before closing this.

**Comment by fajohn** [comment]
Oh well joys of MS licensing issues. Recommendations for running NUnit tests in VS Code?

**Comment by CharliePoole** [comment]
Well, you could simply run the console runner or the NUnit gui (but that's still pre-production).

I have been meaning to try to work on ways to do coding in vscode as I myself move away from Microsoft tools. But don't tell anyone. 😄

**Comment by CharliePoole** [comment]
Oh! This is funny. When I posted the link to the #develop issue, I just copied it without reading. I didn't see I had already commented on it and offered to help. As you see, nobody ever responded. Ah well.
