### ISSUE TITLE
Getting WorkerId inside Assert.Throws / DoesNotThrow returns null instead of previous non-null value

### ISSUE THREAD

**Issue by jtomkiew-ITM** [nunit/docs#190]
In NUnit versions 3.6.0 and 3.6.1 this test fails:

```cs
[Test]
public void GetWorkerIdTest()
{
    var workerId = NUnit.Framework.TestContext.CurrentContext.WorkerId;
    Assert.That(workerId, Is.Not.Null);

    Assert.That(NUnit.Framework.TestContext.CurrentContext.WorkerId, Is.EqualTo(workerId));

    Assert.DoesNotThrow(() =>
    {
        Assert.That(NUnit.Framework.TestContext.CurrentContext.WorkerId, Is.EqualTo(workerId));
    });
}
```

Result:

```
Expected: No Exception to be thrown
But was:  <NUnit.Framework.AssertionException:   Expected: "Worker#2"
But was:  null
```

The assembly has set `Parallelizable(ParallelScope.Fixtures)`.

In previous versions (3.4.1 and 3.5.0) this test passes.

**Comment by CharliePoole** [comment]
I'm not clear about the purpose of this test. It appears that the first two asserts pass correctly. The second seems to fail because of the nested Asserts. The isolated execution context created by Assert.DoesNotThrow is apparently not populating the TestWorker field. 

This is a bug, but unless you have a strong motivator for why you want it to work, it's quite low priority.

**Comment by CharliePoole** [comment]
Issue moved to [nunit/nunit #2157](https://github.com/nunit/nunit/issues/2157) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CharliePoole** [comment]
Ah... wrong repo... moved to NUnit repo
