### ISSUE TITLE
Null TestContext.CurrentContext.Test.Properties with Sequential test

### ISSUE THREAD

**Issue by inadaze** [nunit/docs#192]
When creating a sequential test, the TestContext.CurrentContext.Test.Properties is null when running the test.  I am using the Properties bag to retrieve the Test(Description = "") string where I store the test id for an external application.

**Comment by CharliePoole** [comment]
Do you mean a parameterized test?

**Comment by inadaze** [comment]
Yes, sorry.  Parameterized test using the Sequential Attribute.

Example for clarity (hopefully with no mistakes) :
`
        [Test(Description = "12345"), Sequential]
        public void TestSomething([Values(true, false)] bool someFlag)
        {
            Assert.IsTrue(someFlag);
        }

`

**Comment by CharliePoole** [comment]
This is confusing and is a known problem WRT usability. If you use either the `TestAttribute.Description` property or the `DescriptionAttribute` your description is applied to the `TestSomething` test suite, which contains the two tests. The tests don't get any description.

If you use either `TestCase` or `TestCaseSource`, you can apply the attribute directly to the individual cases, giving each one a separate description.

In the case of your example, since there is only one parameter, you could easily use TestCase, but that may not always be helpful.

See nunit/nunit#1194 for more about this.

**Comment by jnm2** [comment]
I also really like doing:
```c#
[TestCase(true, TestName = "{m}(with some flag)")]
[TestCase(false, TestName = "{m}(without some flag)")]
public void TestSomething(bool someFlag)
{
    Assert.IsTrue(someFlag);
}
```

It'll show up as `TestSomething(with some flag)` and `TestSomething(without some flag)`.

**Comment by inadaze** [comment]
Thanks for the feedback!  I was not familiar with the difference between Test and TestCase.  Thanks!
