### ISSUE TITLE
Filename collision issues

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/docs#2]
A number of links appear to have broken with the transfer to the new wiki. Various side-bar links in NUnit Docs now point to Adapter Docs.

I have never used a GitHub wiki, but it appears that filenames need be unique? ([Ref StackOverflow](http://stackoverflow.com/questions/11088285/github-wiki-directories)) In which case prefixing each file with the project name might be necessary? Would be happy to sort that if it's necessary.

Additionally, all images in the NUnit Docs section are missing - I presume they DO observe directory structure, but need to be relative to root.

**Comment by CharliePoole** [comment]
@ChrisMaddock Thanks for finding this! I fixed the duplicate filenames by changing them in the adapter. 

The images were an interesting problem. It turns out that page references work relative to the page that contains them, so `[[images/nunitTestAdapter.png]]` is just fine. However, image references in this form:

```
![Screen shot of nunit-console](nunit/images/console-mock.png)
```

are relative to the base of the wiki!

As I move ahead in developing this, we may need  to systematize things a bit more.
