### ISSUE TITLE
Need a "Building and testing" doc

### ISSUE THREAD

**Issue by jnm2** [nunit/docs#215]
I think we should have a wiki doc listed first in the https://github.com/nunit/docs/wiki/Team-Practices#technical-practices section that instructs people to look for the repo-specific `BUILD.md`.

This is the first place @OmicronPersei looked for clues when he was trying to figure out what to do with the failing tests in `nunit.testdata-*`. It would be great to document that repo-specific info in each repo's `BUILDING.md` and if people follow the link to the developer wiki from README.md or CONTRIBUTING.md, they'll have a quick path to what they need to know.

Thoughts?

**Comment by CharliePoole** [comment]
AhHa! Here is a hint to the nature of the problem in @OmnicronPersei 's issue on NUnit! Somebody please add it to the issue (# is not handy to me right now).

As we have discussed before, I have slowly been getting rid of much of the old cruft in the dev section of our wiki. Maybe I should record that fact in an Epic, of which this can be part. That way, it won't just be in our heads (or not) 😸 

I think the idea of having common build info __somewhere__ is good. Where that __somewhere__ should be depends on how much we have that's common. Anyway, this issue is a good idea, wherever the general docs end up.

@jnm2 What do you mean by design. We usually mean "can't code this yet, as design is needed." Is there anything preventing your (or somebody else) simply creating the page? If it's just agreeing that we need one, I'm with you. I think I would use the top-level technical practices page rather than creating a new one however.

**Comment by jnm2** [comment]
> I think I would use the top-level technical practices page rather than creating a new one however.

Yes! I like this idea.

#### Technical Practices
<table>
<tr><td>Building and testing</td><td>See BUILD.md in each repository.</td></tr>
<tr><td><a href="https://github.com/nunit/docs/wiki/Coding-Standards">Coding Standards</a></td><td>Describes coding standards used in NUnit.</td></tr>
<tr><td><a href="https://github.com/nunit/docs/wiki/Best-practices-for-XML-documentation">Best practices for XML documentation</a></td><td>Guidelines to consider when dealing with public APIs.</td></tr>
<tr><td><a href="https://github.com/nunit/docs/wiki/Standard-Defines">Standard Defines</a></td><td>Lists standard defines used in building the NUnit projects.</td></tr>
<tr><td>...</td><td>...</td></tr>
</table>

If we do this, we're committing to maintain a BUILD.md in each repository which I think is a good thing.

By `design` I meant "is this a high-level documentation structure we should start acting on?", versus just a adding a wiki page which doesn't affect the way we do documentation in the repositories. I wish there was a cross-repo tag. I might have used that instead.

**Comment by CharliePoole** [comment]
@jnm2 
Looks good to me.

FYI, I generally just do the page and then add a comment asking people to check what I did before closing the issue.

**Comment by CharliePoole** [comment]
Re: Committment to a Build md in each repo... 

I thought we already made that decision. I didn't agree, but I have accepted it as made.

**Comment by jnm2** [comment]
Closed in https://github.com/nunit/docs/wiki/Team-Practices/_compare/11d918eddb4060847880b80a95b89e9add230e58...090419d8e66a4b16bd3c006ff60cfb6cfa18643a
