### ISSUE TITLE
Local method naming standards

### ISSUE THREAD

**Issue by jnm2** [nunit/docs#225]
See: https://github.com/nunit/docs/wiki/Coding-Standards#naming

Any objection to me adding this to the notes section for Methods?

> This includes local methods.

(I assume no one would be confused, but some people think of them as locals rather than methods because they are implemented as delegate locals over a compiler-generated closure, or when possible, compiled into the IL of the containing method. From a C# mental-model point of view, they are methods.)

**Comment by jnm2** [comment]
I assume no one would be confused, but some people think of them as locals rather than methods because they are implemented as delegate locals.

**Comment by CharliePoole** [comment]
No special objection but I get the general feeling that you want these to be much more precise than I like to see and perceptive to a perhaps unhealthy degree.

IME a coding standard needs to say only enough to provide a foundation for discussion during code review. I realize that some dev find that uncomfortable because they consider changes in code review as some sort of black mark. They just need to get over it.

**Comment by jnm2** [comment]
Alright, not sure this is important.
