### ISSUE TITLE
Fix nUnit Links in Console Release Notes

### ISSUE THREAD

**Issue by akamud** [nunit/docs#229]
Most of the links are pointing to the old organization.

https://github.com/akamud/nunit-docs-wiki/commit/63b558d5b2f081b61dc84e22ce4fe0b208e08c1c

**Comment by jnm2** [comment]
@nunit/core-team How do we usually handle this? Do we give wiki access or just pull and push ourselves to simulate a PR?

**Comment by CharliePoole** [comment]
If we wanted to fix it, one of us should just take it and push it. However, I don't think we do but should do something else.

Back in May, @tom-dudley modified the page so that the numbers for each issue became links. That complicated the creation of the release notes and gave us one more thing to keep up to date. Earlier release notes (NUnit 3.5 and earlier) continue to use simple numbers.

If users want to browse the actual issues that were part of a release, GitHub provides that by looking at the closed milestone. All the same issues are listed there and automatically link to the right place.

I suggest we eliminate the links entirely before we get to a new release. It's most easily done by editing the page in the wiki itself. Both the console and the framework page are affected.

**Comment by jnm2** [comment]
That seems the most scalable solution unless we want to use a tool.

**Comment by akamud** [comment]
I recently stumbled upon this tool: https://github.com/GitTools/GitReleaseManager

Not sure if it is what you need, but might be useful.

**Comment by jnm2** [comment]
@rprouse, have you looked at this? ^

**Comment by rprouse** [comment]
@jnm2 that tool looks useful. I've created a similar tool that exports the issues from the current milestone in the formats I need to streamline creating the CHANGES.txt and the release notes. My tool spits out the issues either linked or unlinked depending on the need.

I think we should fix the above issues, but do we need to go back and delete all the links? How often are we going to move repositories? If we split as we did with the console, the links to the old issues will remain correct.

**Comment by CharliePoole** [comment]
We had only numbers for many years and nobody ever asked us for links. Deleting the links would take about 10 minutes, since they are only present in the two files (framework and console) that contain release notes for version 3.5 and later.

Personally, if I had noticed this change back when it was done, I would have voted against it. It seems to me we are solving a problem that doesn't exist. Of course, you've already written the tool that supports it and you can't get that time back again now. 😦 Without that recent change, of course, you would not have had to write code to support it.

We all (developers) have a tendency to complicate things that don't need to be complicated.

**Comment by dialex** [comment]
I'm trying to upload a fix I did for file `nunit/Console-Runner.md` but I can't push it because I don't have privileges. If I try to make a fork of your repo, the wiki files are not pulled. This basically makes impossible for the community to fix/update/improve the documentation, which leads to dead doc.

Can you please find a way to improve this? Am I _n00bly_ missing something?

**Comment by CharliePoole** [comment]
Yes, you are. 😸 

As you learned, GitHub doesn't make it easy to do this via a fork, so we don't work that way. Folks ask for and get permission to edit the wiki and we give it to them. We review the change they made after the fact. Best approach is to indicate in the issue what you are wanting to change, then somebody will give you the permission.

The alternative approach works well for __programmers__ wanting to contribute docs, but not so well for non-programmers, of whom there are lately many using NUnit.

Note that you can clone the wiki itself, rather than the whole repo, but there's no way to create a PR for the changes.

**Comment by dialex** [comment]
Oh, I did not know you were such an open-minded group, I assumed (wrongly) only your team had permission and no one else. Nice!

> Note that you can clone the wiki itself, rather than the whole repo, but there's no way to create a PR for the changes.

Yup, tried that and failed :P 
In the meantime I deleted my PR. It was quite small, just adding an hyperlink from `nunit3-console`to the respective repo, on the releases tab. I thought it could help guide beginners.

**Comment by CharliePoole** [comment]
@rprouse This has been here for a while so I edited the page. But since it may indicate a fault in the process of generating the release notes I'm thinking you should take a look at it before closing.

**Comment by rprouse** [comment]
Thanks @CharliePoole. I think it was just a glitch in the process. I checked the tool that I use to generate the links and it is correctly linking the issues now. It might have been an early copy/paste error.

**Comment by mikkelbu** [comment]
The same problem has occurred in the nunit-console 3.8 release. So I've changed the following
```
#### Issues Resolved

 * [6](https://github.com/nunit-console/nunit-console/issues/6) TypeLoadException in nunit3-console 3.0.1
 * [93](https://github.com/nunit-console/nunit-console/issues/93) Update Readme with information about the NuGet packages
 * [111](https://github.com/nunit-console/nunit-console/issues/111) Provide better info when AppDomain won't unload
 * [116](https://github.com/nunit-console/nunit-console/issues/116) NUnit 3.5.0 defaults to single agent process when using an nunit project file
...
```
into 
```
#### Issues Resolved

 * [6](https://github.com/nunit/nunit-console/issues/6) TypeLoadException in nunit3-console 3.0.1
 * [93](https://github.com/nunit/nunit-console/issues/93) Update Readme with information about the NuGet packages
 * [111](https://github.com/nunit/nunit-console/issues/111) Provide better info when AppDomain won't unload
 * [116](https://github.com/nunit/nunit-console/issues/116) NUnit 3.5.0 defaults to single agent process when using an nunit project file
...
```

**Comment by rprouse** [comment]
Thanks, clearly my program that generates the links needs fixing. I will update it, but I should have noticed.

**Comment by rprouse** [comment]
I have fixed the program that generates the links, I was using repo twice instead of `org/repo` when generating the links. It won't happen again, so closing.
