### ISSUE TITLE
TextFixtureSetUp

### ISSUE THREAD

**Issue by yetibrain** [nunit/docs#232]
On URL https://github.com/nunit/docs/wiki/TestFixtureSetUp-Attribute the Topic is about the TestFixtureSetUp Attribute but this is beeing read:

The TextFixtureSetUp attribute has been deprecated, use OneTimeSetUp Attribute instead.

TextFixtureSetUp ???

**Comment by jadarnel27** [comment]
The documentation you linked to is related to NUnit 3.  You can read more details about the history (and deprecation) of the TestFixtureSetUpAttribute here: [SetUp and TearDown Changes](https://github.com/nunit/docs/wiki/SetUp-and-TearDown-Changes)

So the documentation on that page is (correctly) telling you that you should you use OneTimeSetUp instead of TestFixtureSetUp (which only exists for backwards compatability purposes).

Does that answer your question?

**Comment by yetibrain** [comment]
If that documentation is obsolete yes. I just noticed the difference between TestFixture... and TextFixture...

**Comment by jadarnel27** [comment]
Oh, I see you were pointing out a typo!  Okay, that's fixed now.  Thanks for reporting this!

**Comment by yetibrain** [comment]
Yes, just a typo. Fixed already, ok. Great! Thank you.
