### ISSUE TITLE
Standard Defines page is out of date

### ISSUE THREAD

**Issue by jnm2** [nunit/docs#245]
For the framework repo, it should point you to https://github.com/nunit/nunit/blob/master/BUILDING.md#defined-constants

https://github.com/nunit/docs/wiki/Standard-Defines

What should we do for the other repos?

**Comment by CharliePoole** [comment]
The link to #defined-constants doesn't seem to exist.

Also... why would you point the page anywhere rather than deleting it, if you've decided to not use the wiki for this purpose?

**Comment by jnm2** [comment]
It will exist upon merge of https://github.com/nunit/nunit/pull/2607 (which I expected to merge by now, but just had to kick the AppVeyor build).

If the page is not relevant to other repos it would make the most sense to delete it and perhaps replace links to it with links to BUILDING.md.

**Comment by CharliePoole** [comment]
I'm pretty sure that the only links are in the wiki menu.

Originally, I set up the page because I thought that this should be common to all projects, which is why it's separate from any individual project in the menu.

That's not the case any longer. You all decided to have standards per project and keep them in building.md so the page basically has no force any longer. Having it still exist, however, gives the impression to users that it should be followed, which is confusing, especially if there is conflicting information in building.md.

I think this is true for all the pages under the heading Developer Info. Until recently, I was taking the _de facto_ responsibility for them. Probably somebody else needs to do that now.

**Comment by jnm2** [comment]
I agree. Deleted this page in https://github.com/nunit/docs/wiki/_compare/5c45f5b79aa2b48c44dd8eef10770047c74177be.

**Comment by CharliePoole** [comment]
I edited the menu page to remove the reference. Also created issues for other stuff that needs deleting, moving, revising, etc. in this section of the wiki.
