### ISSUE TITLE
Adding-New-Projects page is obsolete

### ISSUE THREAD

**Issue by jnm2** [nunit/docs#254]
Can we simply delete https://github.com/nunit/docs/wiki/Adding-New-Projects? We've made so many changes and it's so specific to the framework repo.

/cc @rprouse

**Comment by CharliePoole** [comment]
The page is entirely obsolete, I believe. I wrote it to deal with the unique problem of adding new platforms to the framework build, particularly since we had to manually edit the proj file to use a separate intermediate directory. When we stopped having to do that, I think the page became both wrong and unnecessary.

You should be sure to remove the link to it as well, of course.

**Comment by CharliePoole** [comment]
BTW all this dev stuff has needed review. I started doing it and removed a bunch of stuff up to the point where I was no longer the project lead. Somebody else should take it on.

**Comment by jnm2** [comment]
Done in 6e7d58a.
