### ISSUE TITLE
Updating copyright for edits in new year and correcting every attribution

### ISSUE THREAD

**Issue by jnm2** [nunit/docs#255]
Now that we have a 2018 edit, we should probably update the copyrights.
**Also, every single one of the attributions is wrong.**

### 1. NUnit section footer

> <p align="center">Copyright © 2017 NUnit Software</p>

([license 1](https://github.com/nunit/nunit/blob/master/LICENSE.txt), [license 2](https://github.com/nunit/nunit-console/blob/master/LICENSE.txt)) Remove? Update to the following?

> <p align="center">Copyright © 2018 Charlie Poole, Rob Prouse</p>

### 2. Xamarin section footer

>                          Copyright (c) 2016 NUnit Software

([license](https://github.com/nunit/nunit.xamarin/blob/master/LICENSE.txt)) Remove? Update to the following?

> <p align="center">Copyright © 2018 NUnit Project</p>

### 3. Test Generator section footer

>                          Copyright (c) 2016 NUnit Software

([license](https://github.com/nunit/nunit-vs-testgenerator/blob/master/license.txt)) Remove? Update to the following?

> <p align="center">Copyright © 2015-2018 Microsoft, Terje Sandstrom</p>

### 4. Sidebar NUnit > License link

> **Copyright (c) 2004-2015 Charlie Poole**

(https://github.com/nunit/docs/wiki/License)

([license 1](https://github.com/nunit/nunit/blob/master/LICENSE.txt), [license 2](https://github.com/nunit/nunit-console/blob/master/LICENSE.txt)) I say we delete the page (purely a maintenance burden) and replace the sidebar link with:

```markdown
[Framework License](https://github.com/nunit/nunit/blob/master/LICENSE.txt)
[Console License](https://github.com/nunit/nunit-console/blob/master/LICENSE.txt)
```

### 5. Sidebar VS Test Adapter > License link

> **Copyright © 2015-2016 Charlie Poole**

(https://github.com/nunit/docs/wiki/Adapter-License)

([license 1](https://github.com/nunit/nunit-vs-adapter/blob/master/LICENSE.txt), [license 2](https://github.com/nunit/nunit3-vs-adapter/blob/master/LICENSE.txt)) I say we delete the page (purely a maintenance burden) and replace the sidebar link with:

```markdown
[NUnit 2 Adapter License](https://github.com/nunit/nunit-vs-adapter/blob/master/LICENSE.txt)
[NUnit 3 Adapter License](https://github.com/nunit/nunit3-vs-adapter/blob/master/LICENSE.txt)
```

**Comment by CharliePoole** [comment]
Items 1, 2 and 3 relate to the licensing of the documentation, not of the software. Historically, all the documentation was licensed either to me personally or to my company NUnit Software. As part of our governance discussion, I indicated that it could be copyright to the NUnit Project instead.

We should verify that the assignment of copyright is sufficiently documented for our purposes. I think it is but I'll take a further look to make sure. Anyway, for 1, 2 and 3, I suggest

```
Copyright 2018, NUnitProject. <LICENSING>
```

where licensing either says "All Rights Reserved" or indicates some licensing like CC. I had reserved all rights in the past but I don't think that's what we want today.

BTW for 2 and 3, the use of NUnit Software was an error in the first place, since I didn't write either of those. Or maybe we decided to be consistent for some reason. 😸 

In the case of the adapters, there's a bit of a twist. I wrote one set and Terje wrote a different set. I don't know which documentation is included in the wiki right now. I'm happy to give my rights away to the NUnit Project if it's my pages.

Items 4 and 5 actually pertain to the software licenses and I agree with your approach.

**Comment by jnm2** [comment]
Rather than `NUnit Project` can we say `NUnit docs contributors`?
I like [CC BY](https://creativecommons.org/licenses/by/4.0/) or [CC BY-SA](https://creativecommons.org/licenses/by-sa/4.0/). Should we discuss that here or in a separate issue?

**Comment by CharliePoole** [comment]
Here's an excerpt from our governance discussion on copyright...

| Group     | Repo                      | Copyright | Action |
|-----------|---------------------------|-----------|-----------|
| ...      | ...                    | ...   |
| Web       | nunit.org                 | Charlie   | Change to The NUnit Project. Use CC.
|           | docs                      | Charlie   | Change to The NUnit Project. Use CC.
|           | governance                | None      | Change to The NUnit Project. Use CC. **DONE**
|           | nunit.github.io           | nunit.org | Change to The NUnit Project
|           | resources                 | nunit.org | Change to The NUnit Project
| ...      | ...                    | ...   |

We are using CC BY-NC-SA on the web site.

**Comment by jnm2** [comment]
What's the reason for the non-commercial restriction on docs? It doesn't match with our philosophy of the code itself (MIT).

**Comment by jnm2** [comment]
What's the reason for the non-commercial restriction on the website? It doesn't match with our philosophy of the code itself (MIT).

**Comment by CharliePoole** [comment]
This would be a governance issue ultimately, but if we can get the right people (Core Team) all commenting here that works for me as well.

The issue and discussion about copyright started when I was leading the Core Team. While it was still ongoing, Rob was named as the chair of the Core Team and I stopped working on the copyright issue.

We discussed using CC BY-SA in the governance issue. I'm only reporting what I currently see on the website. 😸 @rprouse can you clear this up?

**Comment by CharliePoole** [comment]
BTW as the original copyright holder on a lot of this stuff - software and docs both - I've been waiting for the point where we are fully part of the .NET Foundation and I can get advice from them as to the proper form of licensing or reassigning my own copyrights. That would make things much simpler.

**Comment by jnm2** [comment]
Taking my name off till we decide on the docs license.

Should I want for a quorum before doing steps 4 and 5 or is this stuff pretty low-risk?

**Comment by CharliePoole** [comment]
I don't see any issues with 4 and 5. I don't think you had to take your name off but I also don't think we can do anything till @rprouse indicates whether his understanding of our past decisions is different from my memory.

**Comment by rprouse** [comment]
We went with CC BY-SA to prevent people from copying large portions of our documentation into a book or onto a website that makes money. I am fine with people creating commercial software with NUnit and even including it as a part of commercial software like NCrunch or TestDriven.NET, but the idea of people taking large portions of our docs feels different to me.

We had a short discussion when we selected the CC license, but I don't think anyone had strong opinions. I don't. For now, let's stick with CC BY-SA and if anyone has strong feelings about it, we can discuss in a separate governance issue.

For 1, 2 and 3, those are the attribution names we came up with, although 2 was probably a mistake. I wrote it, so 2 could be in my name. As for updating the year, I do that as part of the release process, see https://github.com/nunit/docs/wiki/Packaging-the-Framework#update-copyright-year, so I don't think it needs to be done here.

I also think 4 and 5 are good ideas, go ahead.

**Comment by jnm2** [comment]
> CC BY-SA 

I like BY-SA, nor do I have a strong opinion. Just clarifying: not CC BY-SA-NC for docs?

**Comment by rprouse** [comment]
Sorry, we do currently have BY-NC-SA on the website which was mainly selected for the docs. We should probably stick with that for now. If we want to debate, we can do that separately.

https://creativecommons.org/licenses/by-nc-sa/4.0/

**Comment by jnm2** [comment]
If I understand right, 1, 2 and 3 have to do with docs and not the code. I updated the NUnit Framework docs in 2018. Am I right that this is a good time to bump the doc copyright years to 2018 all at once? Or just the one? Or none?

Is this what you're thinking?

Framework/console docs:

> <p align="center">Copyright © yyyy NUnit Project – Licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a></p>

Xamarin docs:

> <p align="center">Copyright © yyyy Rob Prouse – Licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a></p>

Test generator docs:

> <p align="center">Copyright © yyyy NUnit Project – Licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a></p>

Double checking, I might be getting lost.

**Comment by CharliePoole** [comment]
@rprouse What about my original question about the legacy docs?

BTW, my comment about as to what I thought we decided was understated. I was actually quoting from the copyright issue in the governance repo. Unfortunately, it's only a comment in the discussion with a table that I created and updated as we went because we never did a final draft.

**Comment by rprouse** [comment]
@CharliePoole I thought we had decided that the legacy docs could go under the CC BY-NC-SA 4.0 License and by copyright you and I as the website now reads. I assume we can leave them that way? Do you disagree?

@jnm2 I'm not sure we as a team ever made a decision about the current docs, but I think they should all have the same CC BY-NC-SA 4.0 License to the NUnit Project, not to me. Does anyone disagree?

**Comment by jnm2** [comment]
@rprouse No, I like that. Should we get a @nunit/core-team quorum?

If it sounds good to everyone, I'd change all footers, including the year, to:

> <p align="center">Copyright © 2018 NUnit Project – Licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a></p>

Correct?

**Comment by jnm2** [comment]
Or could it be:

> <p align="center">Docs Copyright © 2018 NUnit Project – Licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a></p>

**Comment by ChrisMaddock** [comment]
v1 looks good to me. 

Agreed on nuint.xamarin being NUnit Project. I wrote one page, Rob wrote one, and the third was contributed by the community - so I think NUnit Project is appropriate there. 😄

**Comment by CharliePoole** [comment]
@rprouse The last update to the table in the discussion thread for nunit/governance#12 shows what I cited above. There is no mention of the legacy docs. I believe that's because I had not planned for them to move to the new web site at that time. That happened subsequently.

Because I don't always remember the details of our many discussions, I rely a lot on the saved docs and discussion threads. I have searched my email for some private discussion between you and me that would
indicate I had agreed to transfer ownership to you. If there was such a discussion, I would of course honor it but I can't find one.

I'm guessing that you may have been applying the discussion of the software license to the documentation. They have always been separate, however. What I'd like most immediately out of this discussion is to know if you remember something specific that I have forgotten. I think that would be important before breaking any new ground around what might be done with this.

I see that @ChrisMaddock has reopened nunit/governance#12. Should we discuss this there or continue here?

**Comment by jnm2** [comment]
I added footers for every page. Wiki branch standing by to merge; please eyeball: https://github.com/jnm2/nunit-docs-wiki/compare/nunit/docs%23255

**Comment by CharliePoole** [comment]
It looks good to the extent I can tell without actually seeing the wiki. We can check again after you post the changes.

**Comment by jnm2** [comment]
Oh, I could push that! Hang on.

**Comment by jnm2** [comment]
https://github.com/jnm2/nunit-docs-wiki/wiki

**Comment by CharliePoole** [comment]
Looks good to me!

**Comment by OsirisTerje** [comment]
Sorry for dropping in now and not earlier.   
What exactly do we mean by NUnit Project?    When we have assigned copyright to NUnit Project, who exactly do then have the right to change later?  Do we mean the core team?  And if so, is that clearly stated somewhere?

**Comment by CharliePoole** [comment]
In our discussion, we meant it as the overall project - everything we publish under the nunit organization - with the decisions made by the Core Team.

I originally argued that all copyrights should be in the name of some legal entity (person, business, foundation, etc.). In discussions, it came to be that we agreed on "The NUnit Project" for use with certain things. These were generally things - it seems to me - that we cared less about or about which we didn't envision any argument arising.

As mentioned somewhere back in the comments, I was originally writing a copyright.md that would spell out the answers to the questions you are asking. Because I was doing it in the role of Core Team chair, I stopped when a new chair was elected. Subsequently, the Core Team felt we didn't need to do any more about this, so we stopped.

This is just my personal view of how we got here and others may see it differently. My personal view of copyright is that using extra-legal entity names as copyright holders is somewhat shaky but can probably be made to work. The basic question you are asking about changing the copyright is an important one. Another is this one: Who can take action against anyone who violates the copyright?

**Comment by OsirisTerje** [comment]
I think it is wise to define these things now when we are changing.   

For the code parts, I think it is wise to keep them to persons.  It also is a bind the other way.  

For documentation, and legacy stuff, we could use NUnit Project, but we should clearly define what that means legally, e.g. that it is a term meaning whoever is currently the Core Team, and specify if we mean "one of" or "all of". 

Al thought a bit on the side, I checked some .Net Foundation projects and noticed some kept the copyright with the original persons, and some shared it with .net Foundation in the copyright, and some put it all over to .net Foundation.  The two first ones seemed to be in majority for those I checked.   I find the two first ones better than the latter, it is easier to take action if needed.

**Comment by CharliePoole** [comment]
FWIW, over the 13 years during which I was the lead of the project, I've had to deal with license violators about half a dozen times. So it's not common, but it does happen. Of course, with NUnit V2, the license put an extra demand on folks - they had to give us credit. With MIT that's not an issue.

I actually did deal with one documentation violation - a published book that excerpted parts of the documentation I had written, without getting my permission. So again, it can happen.

I'm comfortable with the past decisions we made that involve assigning copyright to the software to other __people__ - you and Rob specifically. I'm concerned that I haven't actually done it in a proper legal way but we have a separate thread where that's being discussed offline and I think it will get fixed.

Where we decided to simply put the name The NUnit Project on the copyrights, I'm a bit worried. Lots of projects do that sort of thing without worrying, of course, but I'd feel better if we at least documented what we mean by that, as you suggest. And if the .NET Foundation could help us make the NUnit Project into something with actual legal existence I'd feel even better!

**Comment by jnm2** [comment]
Is everyone satisfied so far with https://github.com/jnm2/nunit-docs-wiki/compare/nunit/docs%23255 and https://github.com/jnm2/nunit-docs-wiki/wiki?

**Comment by OsirisTerje** [comment]
@jnm2 NUnit Project is not defined.  Shouldn't we do that first?

**Comment by jnm2** [comment]
It currently says "NUnit Software" which is also undefined, but I tend to agree with you. Where would we define it?

**Comment by CharliePoole** [comment]
@jnm2 Actually, "NUnit Software" is quite well defined. It's the name of a company I own. More precisely, it's a DBA of Poole Consulting.

Background: When I first began working with Microsoft on the adapter, back in 2010 or 2011, they were not well set up to allow a __person__ to be a "partner." That's when I started using "NUnit Software" for a lot of things. Some of that still hangs around today.

Depending where you see it, I may have added "NUnit Software" to some notice OR somebody else just copied and pasted without knowing what it meant.

When we first started discussing copyright in the Core Team (@jnm2 I think before you joined) I indicated I wanted to separate the things that __intentionally__ had "Charlie Poole" or "NUnit Software" from those where it may have been put there accidentally. I don't think we entirely finished that phase.

Look at the discussion on nunit/governance#12 for at least some of the discussion. I'm afraid a lot of it was in email, however.

**Comment by CharliePoole** [comment]
"Where would we define it?"

We can't do much to legally define an extra-legal entity. IMO the most we could do would be to create a governance document that describes what we mean by the term. It would probably say that the Core Team is empowered to exercise all rights pursuant to a vote.

@ChrisMaddock re-opened nunit/governance#12 so that would probably be the best place to discuss the question.

**Comment by jnm2** [comment]
Can I move ahead with this in everything except keep the name NUnit Software for the time being? We can update that later depending on https://github.com/nunit/governance/issues/12.

> <p align="center">Copyright © 2018 NUnit Software—Licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a></p>

**Comment by CharliePoole** [comment]
Not sure what the issue with NUnit Software is or why it's still there. Since it's my company, I'll go through later today and just remove it. AFAICS, each section has either the NUnit Software footer (which it should not) or no footer. It will be up to you guys to figure out what you actually want the footers to say. I __thought__ we had agreed on "The NUnit Project".

**Comment by rprouse** [comment]
Talking to Jon this week, they will soon be able to register nunit.org as a company under them to allow us to have signing certificates. Since that will be a legal entity, we could use that. @charliepoole, he says will not have any legal conflict with your company. That was my first question :grinning:

**Comment by jnm2** [comment]
I'm so confused. There's conversation going on about what name to use, so why not postpone that part if it's holding this up?

**Comment by CharliePoole** [comment]
Reviewing only the footers in the docs wiki, here's what I find:

1. No general or default footer
2. The nunit directory has Copyright 2017 NUnit Software
3. The xamarin and test-generator directories have Copyright 2016 NUnit Software

Here's what I think it should be

1. There should be a default footer. It should say Copyright 2018(?) The NUnit Project. I think the current year is best on a website, rather than a range of years. As far as the name goes, I thought we decided on "The NUnit Project" in nunit/governance#12 rather than "nunit.org". Am I wrong?

2 and 3. These should not be copyright to my private business. In the case of the NUnit docs, they were originally copyright to me personally but in discussing nunit/governance#12, I indicated my willingness to release the current docs to the project itself. For the other two, I don't know how it got there.

So... here's what I'll do...

1. I'll add a default footer in the root. I believe it will show up on all pages. If not, we can copy it.

2 and 3. I'll delete those footers.

I'm going ahead and doing it because I __really__ want to get my company name out of there and it's very easy for anyone with write access to change what I do if it needs changing.

**Comment by jnm2** [comment]
@CharliePoole Sure, that makes sense. I've had https://github.com/jnm2/nunit-docs-wiki/compare/nunit/docs%23255 ready to go with 'NUnit Project' but it seems we run into legal questions and get bogged down.

**Comment by CharliePoole** [comment]
WRT NUnit Software, there's no legal problem, just a question of fact. NUnit Software has nothing to do with these docs.

There is a fair question about whether to use "The NUnit Project" as the copyright holder, since it's not a legal entity. But since the .NET Foundation is able to make it a legal entity, I think we should go ahead.

I did try to make comments a while back on your file compare, but I didn't have access to do that because it's between two branches of your own repository. One thing I didn't understand is why you were removing some of the software license information from the wiki.

**Comment by jnm2** [comment]
Great! @nunit/core-team, everyone else okay with me pushing the update using the name 'NUnit Project' especially since Charlie would like us to remove the currently-incorrect use of the name 'NUnit Software?'

@CharliePoole 

> One thing I didn't understand is why you were removing some of the software license information from the wiki.

Unless I've made a mistake, I'm only removing software license information referring to the source code of the products, replacing it with direct links to the license of each repo. They were out of date. This gets rid of a maintenance burden. Way back at the top I covered this in 4 and 5 and I remember that being favorable to everyone.

**Comment by CharliePoole** [comment]
I see. That makes sense.

**Comment by ChrisMaddock** [comment]
Yep, sounds good to me.

**Comment by ChrisMaddock** [comment]
This issue looks to now be resolved - the docs now use a single copyright footer, and I would suggest any further work on that copyright belongs under: https://github.com/nunit/governance/issues/12

I'll close, if anyone disagrees (@nunit/core-team), please reopen. 🙂
