### ISSUE TITLE
running test methods within a fixture parallel

### ISSUE THREAD

**Issue by vigneshwar-v** [nunit/docs#27]
is the parallelscope.self started working? Because, I don't see the methods inside a fixture is not running parallel. But, all fixtures are running parallel if I use parallelscope.fixtures

**Comment by ChrisMaddock** [comment]
Parallelization of methods within a fixture has not yet been implemented, the open issue for it is here: nunit/nunit#164

I see on the attribute page it states it is not implemented in 3.0, which may be confusing now 3.2 is released. I'll update this to be non-version-specific - hopefully someone will remember to make the change once it's implemented! (cc @CharliePoole - sensible?)

**Comment by CharliePoole** [comment]
Makes sense to me.

**Comment by vigneshwar-v** [comment]
Yeah make sense.  But may I know,  when this feature can be expected??

**Comment by CharliePoole** [comment]
You'll have to keep tracking the issue that Chris pointed to. We only assign a few issues to each milestone (release) because we never know how many people will put in work during that period. However, we generally finish many additional ones off the backlog. This is an important one, so I'm hoping we will get it into the 3.4 release. For expected scheduile, see the milestones for NUnit at https://github.com/nunit/nunit/milestones
