### ISSUE TITLE
Remove temporary parallelizable page?

### ISSUE THREAD

**Issue by jnm2** [nunit/docs#273]
@AGBrown was brought to https://github.com/nunit/docs/wiki/Parallelizable-Attribute-(New) from Google. I wasn't aware of this page, but it looks like a temporary page and it's less up-to-date than the page linked from Attributes page (https://github.com/nunit/docs/wiki/Parallelizable-Attribute).

Can we go ahead and move its contents to https://github.com/nunit/docs/wiki/Parallelizable-Attribute, and remove this page?

**Comment by CharliePoole** [comment]
@jnm2 While I was on vacation, there was some discussion about the need for a better writeup about using parallelism. I said I'd work on it. Can't remember if the exchange was with you or somebody else.

Anyway, creating an unlinked page is how we have done new rewrites for ages, so that's what I did. After I got busy with the XP conference, I never got back to it. 

The main problem with the existing page is that it gives too much info about options that no user should ever use. I keep seeing people add a parallelscope arg to the attribute when they should just be using it without any argument at all. Often, the argument they choose is what messes up the code.

That said, if this is causing confusion in google searches, we should delete it. Suggestions as to how to reduce the confusion or an alternative approach? I feel like actually creating the page is the best way to get it reviewed, as opposed to using a PR for the docs.

**Comment by jnm2** [comment]
Thanks, I had forgotten that context. If we set the title to (WIP) in the interim, would that perhaps be explanatory enough to people who land there?

**Comment by CharliePoole** [comment]
Works for me! Since the revision has no tracking issue, let's use this one. I'll assign to myself so I don't forget about it.

**Comment by CharliePoole** [comment]
I reviewed the two pages, updated  https://github.com/nunit/docs/wiki/Parallelizable-Attribute and removed the temporary page. The new page is considerably smaller because it avoids listing all the parameters that we tell people not to use. Better not to mention them I think.

The old page is still available in the history if anyone wants to restore some of it.

**Comment by jnm2** [comment]
Looks good!
