### ISSUE TITLE
Wrong command line in Test Selection Language page ?

### ISSUE THREAD

**Issue by marshall777** [nunit/docs#275]
Hello,

On the [Test Selection Language](https://github.com/nunit/docs/wiki/Test-Selection-Language) documentation page, the first paragraph shows the following command line :
`nunit3-console mytest.dll --where "cat == Urgent || Priority == High"`

I think there is an equal sign missing between _--where_ and the filter itself :
`nunit3-console mytest.dll --where="cat == Urgent || Priority == High"`

I tried using the command line showed in this documentation without success and the [Console Command Line](https://github.com/nunit/docs/wiki/Console-Command-Line) page clearly states **--where=** though I ran the command line through Powershell so it might be a issue specific to PS only.

**Comment by CharliePoole** [comment]
Sample command lines in the docs are all tested at the Windows command prompt. Escaping of special characters varies from OS to OS and is possibly different under PowerScript as well. There are other differences too, such as allowing or disallowing the use of '/' to signal an option. NUnit does not parse the command-line itself, but merely gets its arguments from the environment in which the command is run.

In the past, we have avoided providing documentation about how to use different command-lines because (1) it's an area of general knowledge and not nunit-specific and (2) it can get very complicated considering the many ways in which commands may be executed.

The command quoted uses my favorite approach to this option: leaving `--where` separate and quoting the actual argument so I can use special characters and spaces. If that doesn't work for your environment, the solution you found is a good choice.

I'm leaving this open as an issue so that the @nunit/framework-and-engine-team can decide whether to expand the documentation to include information about each OS and possibly PowerScript.

**Comment by mikkelbu** [comment]
In my PowerShell I'm able to use both variants.

```
PS> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17134  112

...

PS> .\nunit3-console.exe .\nunit.engine.tests.dll --where "cat == Urgent || Priority == High2"
NUnit Console Runner 3.9.0
Copyright (c) 2018 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.17134.0
  CLR Version: 4.0.30319.42000

Test Files
    .\nunit.engine.tests.dll

Test Filters
    Where: cat == Urgent || Priority == High2

...

PS> .\nunit3-console.exe .\nunit.engine.tests.dll --where="cat == Urgent || Prior
ity == High2"
NUnit Console Runner 3.9.0
Copyright (c) 2018 Charlie Poole, Rob Prouse

Runtime Environment
   OS Version: Microsoft Windows NT 10.0.17134.0
  CLR Version: 4.0.30319.42000

Test Files
    .\nunit.engine.tests.dll

Test Filters
    Where: cat == Urgent || Priority == High2
...
```

**Comment by ChrisMaddock** [comment]
It think the docs are sufficient here, we don't have the capacity to list options for every possible console runner. Thanks for raising this issue anyway.

**Comment by jnm2** [comment]
@marshall777 To be clear, the issue was not the missing `=` since PowerShell handles that particular example just like cmd does. Mikkel's finding was what I expected. If it's still giving you trouble, we would be interested in getting more info to see what could be going on.
