### ISSUE TITLE
Setting several categories to an iteration

### ISSUE THREAD

**Issue by ilona2610** [nunit/docs#28]
Hi,

I'm using TestCaseData class to run a test with several iterations.
Up until NUnit 3, I was able to set several categories for each iteration by - data.Categories.Add(cat).
In NUnit 3 it was changed to - data.SetCategory(cat) - that can set only one category for each iteration.
How can get the required functionality in NUnit 3?

Thank you!

**Comment by CharliePoole** [comment]
Not changed exactly. SetCategory(cat) is part of the fluent interface and has existed since NUnit V2. NUnit V2 also exposed a Categories property that could be used as you describe. For example, in your data source method you could set the category in either of two ways:

```C#
    yield return new TestCaseData(...).SetCategory("mycat");

    // Equivalent
    var data = new TestCaseData(...);
    data.Categories.Add("mycat");
    // etc.
    yield return data;
```

In 3.0, we removed the categories property - perhaps a mistake if many people were using it. However, you can still do it this way, even though it's slightly more laborious.

```
    var data = new TestCaseData(...);
    data.Properties.Add("Category", "mycat");
    // etc.
    yield return data;
```

Perhaps the simplest alternative is to use SetCategory, ignoring the return value...

```C#
    var data = new TestCaseData(...);
    data.SetCategory("mycat");
    // etc.
    yield return data;
```

Hopefully, this plethora of alternatives explains why we removed the Category property.
