### ISSUE TITLE
Advantages of nunit3 xml over nunit2 xml

### ISSUE THREAD

**Issue by simarust** [nunit/docs#280]
After migrating from NUnit2 to NUnit3 we run nunit3-console with the option `--result=<foobar.xml>;format=nunit2` as we are using the result files for further analysis.
We now wonder what the advantages of nunit3 xml are over the legacy format.
Do we lose any data when we stay with nunit2 xml? Or is there the risk that the nunit3 console runner will not support the old xml format in future?

**Comment by rprouse** [comment]
The NUnit 3 format does support newer features like warnings and multiple asserts better and does contain more information than the NUnit 2 format because it is better aligned with the NUnit 3 framework. We will continue to support the old format for as long as possible, but I would recommend moving to the new format when you can. We maintain the old format for older CI systems and tools that haven't updated to the newer format, but we don't update the old format for new features.

I am going to close this as a question. If you have further questions, post here, we will see it.

**Comment by CharliePoole** [comment]
@simarust Just so you know, the nunit3 format is always produced internally. The nunit2 format is translated from it if you specify `format=nunit2` in your `--result` option. You can specify as many result files as you like on the command-line, so it's possible to have both nunit2 and nunit3 output.
