### ISSUE TITLE
Empty Constraint Typo and Missing Docs

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/docs#3]
On EmptyConstraint:

- The example reads `Assert.Thst`.
- There looks to be some broken inline code formatting later down the page, around \`DirectoryInfo\`.

Below is a quick write up of the two missing empty constraints, just adapted from the EmptyDirectoryConstraint page.
https://gist.github.com/ChrisMaddock/8e3fb6fa1bdf1a7a722e

And lastly, spotted while stealing examples, on CollectionOrderedConstraint:
- There are a number of `&gt;` and `&lt;` in the Modifiers section, 
- The final example is short a bracket.
`Assert.That( sarray2, Is.Ordered.By("Length");`

Thanks!

**Comment by CharliePoole** [comment]
I fixed the typos in EmptyConstraint and assigned the issue to you. You have write access to the wiki now and can just create the pages online.

If you fix minor typos in future, that's fine. Ask for a review after the fact if you feel the change is big enough to warrant it. If you actually want to rewrite rather than correct the text, please get a review beforehand. The easiest way for a single page is to create a separate temporary page. More complex stuff requires cloning, for which I will eventually publish instructions.

BTW, do not try to edit menus online - we have multiple menus in subdirectories and editing them online doesn't actually work correctly.

Soon I'll have a full set of instructions and other people will also gain access, but since you have been pointing out so much stuff, it makes sense to use you as a guinea pig. :-)

**Comment by ChrisMaddock** [comment]
Fair enough, that works for me. :-) Apologies for all the petty issues, I've been noting things down as I run in to them!

Have made these changes. If you are writing the process up: it doesn't appear to be possible to create new pages with the online interface. Doing so puts them in the root directory, which gives them the main side bar - I had to `git mv` the files to the nunit dir and push to show the correct sidebar.

(All cc @CharliePoole, as I still haven't pinned down the logic behind when GitHub sends a notification or not.)

**Comment by CharliePoole** [comment]
Thanks for adding these. I made a small edit to EmptyCollectionConstraint.

I didn't realize that about new pages. I'll have to give it a think.
