### ISSUE TITLE
Explain Apartments

### ISSUE THREAD

**Issue by kaimikael** [nunit/docs#306]
The page on Apartment Attributes (https://github.com/nunit/docs/wiki/Apartment-Attribute) has to be considered somewhat confusing.  It starts by saying: “The ApartmentAttribute is used on a test method, class or assembly to specify that the tests should be run in a particular apartment, either the STA or the MTA.”
There are no further links to explanations of apartments in the context of NUnit testing, nor what MTA and STA are.
I would like a bit more explanation, or at least references to additional reading.

**Comment by CharliePoole** [comment]
In the past, we've always taken the view that it's not up to the MInor docs to explain basic .NET concepts. That's why we just mention such concepts without explanation.

If the @nunit-framework-team wants to do more, my suggestion is that we just provide a link in these cases rather than writing our own explanation.

Obviously, we would want to do more in cases where NUnit interacts with .NET in a non-standard way.

**Comment by mikkelbu** [comment]
I don't see a problem in linking to e.g. https://docs.microsoft.com/en-us/windows/desktop/com/processes--threads--and-apartments, and I agree that we should not spend time explaining concepts that are standard (and are described somewhere else).

**Comment by kaimikael** [comment]
I concede the point that obvious items should not need to be explained, but I have to say that in the half-a-dozen .NET books I looked through just now, only one mentioned apartments (on page 846), and even that didn’t bother explaining what it was, but seemingly also assumed that everybody would know the concept.  It seems I have missed something in my education.

**Comment by CharliePoole** [comment]
@kamikael When I said "basic" I meant it as "fundamental" rather than "elementary." In fact, knowledge of apartments is fundamental to Windows programming in general, but I do understand that folks won't usually encounter it at the start.

In any case, even if a concept is advanced and non-obvious, I don't think we should write it up in any detail in our docs. That's simply because we are not the experts on (for example) apartments. The MS folks are. In addition, we would then have to update those docs any time the functioning of apartments changed from the Microsoft side.

But I do favor a new practice of adding links to other folks' documentation where useful and that's what I did here. I just made the link from the word "apartment" although it could be made more prominent if you or @mikkelbu think it needs to be.

@mikkelbu I'm leaving this open in case you want to edit it further.

**Comment by CharliePoole** [comment]
@kaimikael I came to this stuff from COM, BTW, so that may be why it seems so fundamental to me.

**Comment by kaimikael** [comment]
:-) I’m happy with a link and agree that it is the best solution.

**Comment by mikkelbu** [comment]
@CharliePoole I think it is fine. I'll close the issue now.
