### ISSUE TITLE
Combine VS Adapter Docs

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#31]
It seems that users tend to thing of the adapter as a single thing, even though we have two different extension packages. There's enough similarity in the docs that we may be able to combine them.

This issue is basically the statement of an idea. We should evaluate it generally and then, if we like it, see if we can make it work.
### Current Status

The following is a summary of pages in the two sets of docs and what they contain.

| NUnit 3 Adapter | NUnit (2) Adapter | Content |
| --- | --- | --- |
| Home | NA | Overall documentation Home page |
| NA | General Developer Wiki | Dev Wiki Home page |
| NUnit VS Adapter | Home | Adapter Home page |
| Installation | VS Adapter Introduction | How to Install |
| Usage | VS Adapter Introduction | How to use |
| Resources | VS Adapter Introduction | More info |
| Known Problems | VS Adapter Introduction | Known problems |
| NA | VS Adapter Roadmap | Planned releases |
| Tips and Tricks | Tips And Tricks | Tips and tricks |
| Release Notes | NA | Release Notes |
| License | NA | License |
| Packaging | How to build and package a release | How to package |
| NA | Usage of Labels | Special label for adapter |
### Action Plan
1. Use V3 adapter home and menu structure.
2. Review common pages with the same content. Edit as necessary. Introduce special subsections for V2 and V3 as necessary. Pages affected: Tips and Tricks, Packaging, Installation, Usage, Resources, Known Problems
3. Create Release Notes for V2.
4. Decide whether to maintain Roadmap or to refer users to GitHub milestones. If we keep it, add sections for V2 and V3. Maybe we should have a policy statement about what sort of maintenance we plan on doing for V2.
5. Add Label usage to the developer section.

**Comment by CharliePoole** [comment]
@OsirisTerje I created this so we would have a place to discuss how we want to handle docs. What are your thoughts?

**Comment by OsirisTerje** [comment]
Merging them is a good idea.  It is better to have one place since the basic functionality of these two are the same.  We need to separate out what is specific for the 2.X adapter, and we need to be clear that NUnit 2.X should use the 2.X adapter, and NUnit 3 the 3.X adapter.  

The breakdown you have above makes sense.  I see labels are not in the 3.X column, but we still need the specific labels for the adapters, so this should be included. 

There are some specific concerns around the visual studio integration.  I think it would be good to have a section for that - a developer centric section, but only related to the integration details, like the discussion we had around use of the settings, and the different concerns there.  So a For the Developer section would be nice.  That section could also detail the approaches for debugging the adapter. 

About roadmaps, I think the Milestones are good enough for that.  We don't need to duplicate what already exists, better to refer to the milestones when we need for information.  That could possibly be a separate section too, comments on the roadmap with references to the milestones ?

**Comment by CharliePoole** [comment]
OK, I'll do what I can do and ask you for other individual items. I think it's OK for either of us to post changes and then ask the other guy to review, since the wiki saves the history anyway.

There is a developer section already, right now I only have packaging in it but I agree we need labels as well. See action item 5 in the earlier note. I'm not 100% clear about the visual studio integration section. Would it include what we have learned that drives the design, like required naming conventions, etc? I think you may need to fill in some of that stuff.

On roadmaps, I was thinking we need something at a policy level. For example, Rob and I have decided to put out quarterly releases of NUnit itself. For the 3.x adapter, I think we should do the same and put them out right after the NUnit releases. I don't know what the policy ought to be for the 2.x adapter, but there should be one and users should know what it is. These general statements could be short and then link to the milestones.

For all of this, I'll create the pages and put at least some dummy text on them, then ask you to review or fill in as the case may be.

**Comment by CharliePoole** [comment]
@OsirisTerje I'm reviewing / revising this based on our recent conversation. I'll make this issue into a ZenHub Epic with sub-issues for the individual pages.

**Comment by SeanKilleen** [comment]
🧹 Cleanup -- I am closing this issue because:

✅ The VS Adapter has a page on the wiki
✅ The docs appear to be combined
✅ This issue has not been updated for 4 years.

Happy to reopen if I'm missing something; just leave a comment.

**Comment by CharliePoole** [comment]
Should have been marked as done and credit given to @OsirisTerje when he did it.

**Comment by ChrisMaddock** [comment]
I think issues #83-#88 all fell under this too, no? 🙂
