### ISSUE TITLE
Console output from SetupFixture

### ISSUE THREAD

**Issue by officeSpacePirate** [nunit/docs#325]
Is there a way to write output from a SetUpFixture? I tried TestContext.WriteLine() to no avail, but it seems like the wrong approach anyway. I haven't been able to find any documentation on being able to add output to StdOut before and/or after test execution.

As a work around, I am currently writing a file locally which adds several more steps if I want to use the data produced from a test run in a CI pipeline. If this isn't currently possible, I can move this to a feature request in the code repo.

**Comment by CharliePoole** [comment]
You can __write__ to console in the OneTimeSetUp or OneTimeTearDown methods of a SetUpFixture class. However, like all console output from NUnit tests, it is captured by NUnit and transformed into a part of the test result. 

In the case of a SetUpFixture, I'd expect the output to appear in the XML result file as part of the element for that suite. It is also received by the test runner but many test runners choose not to display anything that's not part of an individual test method.

In particular, TestExplorer works that way. Only output from test cases is shown.

One approach to try is using `TestContext.Progress` to create output that is displayed independent of the test result itself. No guarantees there, however, since it's still up to the runner to display it or not.

**Comment by officeSpacePirate** [comment]
@CharliePoole TestContext.Progress.WriteLine() does the trick. Thanks for the detailed response.
