### ISSUE TITLE
Naming collisions

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/docs#33]
There's some new naming collisions in the wiki. I stumbled across it going to the Console-Runner page in NUnit, which seems to be clashing with a dev wiki page - not sure if there are others as well. Not set up to look at it properly right now, so adding the issue so it's not forgotten!

**Comment by CharliePoole** [comment]
Of course! I added a whole new directory and copied in the pages from the dev wiki without first checking for duplicates! I'll get on it.

**Comment by CharliePoole** [comment]
@ChrisMaddock I believe this is fixed. I renamed a bunch of pages. Could you check wherever you saw this and let me know if anything pops up? No need to go through every page, of course.

BTW the developer documentation section is in progress and many of those pages are actually obsolete. I just wanted to get it over into this repo where it's easier to work on it rather than working between two repos.

**Comment by ChrisMaddock** [comment]
Thanks @CharliePoole! Looks good from where I'm at.
