### ISSUE TITLE
Docfx: How to Treat legacy wiki contents?

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/docs#355]
Depends on #341. 

Suggested plan:

* Remove wiki contents in each page, but keep the page itself.
* Add a link on each page to the new page

Outcomes:

* No 404s for users with old links
* No old content to compete with new content
* No SEO confusion.

## To Do 

* [x] Ensure backup of wiki repo (for last-ditch restore effort if needed)

**Comment by OsirisTerje** [comment]
I don't think the old content should be removed.  There are unknown amount of pages, including comments in issues, blogposts, stack overflow, developer communities site and more that may have links to different pages in the wiki.  We don't want them to get 404s.  It is better if we run through all pages, insert a custom sub header for each page with a link to the new page.  The old content can still be there, so that people are not forced to further.  All links inside the wiki however can be converted to point to the new pages.

**Comment by SeanKilleen** [comment]
@OsirisTerje 

> I don't think the old content should be removed...we don't want them to get 404s

Agreed. That makes sense.

> It is better if we run through all pages, insert a custom sub header for each page with a link to the new page

The only reason I'd suggest avoiding the sub-header is for SEO reasons. The wiki has been around far longer and will show up first in many cases. In that case, I'd rather ensure people are being linked to a place with recent content that isn't competing with the older content. 

> All links inside the wiki however can be converted to point to the new pages.

That's a lot of work that I wouldn't recommend undertaking.

**Comment by OsirisTerje** [comment]
About the last one:   The docs are moved over "as is", right?  So the last part of the url will be the same.  Isn't this then a question of search/replace of the first part of the url ?  

If names of the markdown files changes, then of course things go astray.....

**Comment by SeanKilleen** [comment]
Some of the structure has changed. The wiki has one level of hierarchy, for example, and the articles are not necessarily grouped in any meaningful way. So yes, some titles & structure have changed.

**Comment by ChrisMaddock** [comment]
I'm not a big fan of us keeping an outdated version of the docs online, to be honest. I'd prefer there was a simple follow-through link to the up to date page for every page, rather than both the link to the "real docs", and then some old content which may be outdated.

The URL change isn't ideal, but GitHub wiki's don't give us any option to redirect (as far as I know), so I think we just need to do the best we can here.

**Comment by jnm2** [comment]
I'm thinking the same as Chris.

**Comment by SeanKilleen** [comment]
The general consensus I'm hearing here is:

* It is ok to begin replacing wiki contents with links to that content on the docs.nunit.org
* We will not delete the wiki pages, just replace contents, in order to preserve external links to those wiki pages.
* There is some hesitance over losing the old content on the pages, but in general keeping one content source seems preferable.

Does anyone strongly disagree with that assessment?

**Comment by CharliePoole** [comment]
For keeping the old content, we just need some backups. I have one copy locally. Does somebody want to make another one?

As a further reassurance, we could create an old-docs repository and put the wiki there but if we do so, it should be readonly.

**Comment by SeanKilleen** [comment]
@CharliePoole Great point.

I have a copy locally (the git repo). 

I've also zipped it and uploaded to My OneDrive; link here if anyone wants their own copy: https://1drv.ms/u/s!AuaqsrDoMOUHm-Brc-qHxW6CrlwICQ?e=eSqFCE

That should provide many places that have the original wiki source with all changes.

**Comment by CharliePoole** [comment]
@SeanKilleen FYI, the legacy site is the only place that has docs and software for NUnit 2.6.5 through 2.7.1, which I released outside of this project.

**Comment by SeanKilleen** [comment]
Given that:

✅ Charlie has a backup of the wiki
✅ I have a backup of the wiki
✅ The backup is available for download
✅ We have a general consensus
✅ The site is now live at <https://docs.nunit.org>

I intend to proceed with the plan to begin replacing wiki contents with links to their web site counterparts.
