### ISSUE TITLE
Protect master branch

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/docs#393]
Just spotted when trying making an edit that this repository allows committing directly to the master branch.

In most other repos, we have the master branch protected, so that everything has to go via pull request, and it's harder to make a mistake and accidentally push the wrong thing to master. Might be worth turning the same setting on here? What do you think @SeanKilleen?

**Comment by SeanKilleen** [comment]
@ChrisMaddock I agree 100%.

I'll be asking for some overall admin authority for this repo so I can sort out some things like that.

But in the interim if someone wanted to protect the master branch I'd be totally fine with that. 👍

**Comment by ChrisMaddock** [comment]
I think it’s currently only set up for the overall organisation admins in this repo. (Charlie and Rob) 

@CharliePoole - would you mind?

**Comment by CharliePoole** [comment]
@SeanKilleen Have you actually tried this? It would be worthwhile knowing exactly what you can't do. I believe that GitHub intended the Maintainer role for this sort of thing and you should be able to do everything outside of the "danger zone".

However, GH policies are sometimes hard to figure out so let me know if I'm wrong.

**Comment by SeanKilleen** [comment]
@CharliePoole yes I tried this. I do not have access. I'll post screenshots when in able. 👍

**Comment by CharliePoole** [comment]
It may be needed then. Because it's more than any project lead now has, I think there's a governance issue, which I'll create.

One problem all along has been that Rob and I are unlimited by GitHub, and so are not aware of the issues project leads may face.

Meanwhile, I'll set it up as you asked when I get to my computer.

**Comment by CharliePoole** [comment]
There's a great example of what I said about not knowing what security issues others face! I didn't know that most repos have the master branch protected. I thought it was just framework and engine.

**Comment by CharliePoole** [comment]
@SeanKilleen I set it up so that only organization administrators, repository administrators, and users with the Maintain role (that's you) can do a direct push to master. There's quite a bit of flexibility in wha we can allow the Maintainer to do. The repo admin can do a lot of things too, including deleting the repository entirely, which I think is why we have never used it. :stuck_out_tongue_winking_eye:

**Comment by ChrisMaddock** [comment]
@CharliePoole - maybe worth having a look at what permissions my account has on the Engine repo? I have access to these settings in that repo, but nowhere else, which I think is what we’re aiming for. 😊

**Comment by CharliePoole** [comment]
@ChrisMaddock Yes... in fact I believe I set you up as maintainer a short while ago. (Checking...) Ah no! I set you up as admin... I'm happy to do anything that's in the spirit of the governance docs until we clarify it.

Maybe it's useful to keep @SeanKilleen as  in the Maintain role, so he can explore the limits of his authority and let us know. Then I could propose one or the other role as the standard for project leads. Is that OK with you Sean?

@ChrisMaddock Is the danger zone stuff under settings available to you? Could you delete the repo for example? But please don't. :laughing:

**Comment by ChrisMaddock** [comment]
It is. 👍

**Comment by SeanKilleen** [comment]
@CharliePoole here's a permissions reference: https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization -- a nice breakdown of what is enabled by role. Unfortunately, it's not more granular. 

So the actions covered there that I might like to do, and whether or not I can:

✔️ Manage GitHub pages settings (enabling, selecting deployment branch)
❌ Add bots and other useful process-oriented tools
❌ Add repository-level secrets (required for configuring GitHub actions to push to the `gh-pages` branch automatically
❌ Define code owners (for different sections of docs)
❌ Manage branch protection rules

If the NUnit governing team is uncomfortable with me being given those permissions (even temporarily), it's not the end of the world -- things might just take a lot longer to happen as we work to coordinate asynchronously. 👍

**Comment by SeanKilleen** [comment]
FYI, I created https://github.com/nunit/governance/issues/38 so that we can officially discuss.

**Comment by CharliePoole** [comment]
@SeanKillen The governance repository has nothing to do with giving permissions to individuals. It's purpose is to document the general rules by which the overall NUnit Project is governed.

It seemed to me we were making progress right here, but if you don't feel that's the case, please let me know what the problem is. This is the right place to resolve any issue about the documentation project.

You saw me mention the governance repo in earlier discussion because I think that what you, Chris and I are discussing may eventually funnel into a new process document, a general approach to GitHub access for project leads.

**Comment by CharliePoole** [comment]
@SeanKilleen It looks like some of what you want to do is in the web site itself. Am I correct? Or is all of this in the docs repository only? 

Anyway, the web site is our nunit.github.io repository and project, of which Rob is the project lead.

That could end up working in several ways...

1. You just ask Rob to do things. (We sometimes do that for our own projects)

2. You go through a PR process, where Rob will approve the merge. (That's what we mostly do if we want a change to the site.)

3. The two projects merge in some way or another. (The current separation is mostly history)

IMHO you and @rprouse should discuss which is best. The rest of us, including me, would have opinions, if asked, but for me the rule is that who does the work decides how to do it.

**Comment by CharliePoole** [comment]
Looking at the stuff that @SeanKilleen needs to do and comparing it to the GitHub docs, it seems like admin is the necessary level, just as it was for @ChrisMaddock. Looks like @mikkelbu has the same. 

What about you @mikkelbu

**Comment by SeanKilleen** [comment]
Thank you @CharliePoole! This is now complete.

![Screenshot_20200615-061814](https://user-images.githubusercontent.com/2148318/84646435-195a4b80-aed0-11ea-8226-883d8a784971.png)

**Comment by jnm2** [comment]
@CharliePoole 

> I didn't know that most repos have the master branch protected. I thought it was just framework and engine.

@OsirisTerje protected the master branch in the adapter repo when I asked for that after I mistyped a Git command and unintentionally pushed changes to the master branch.
