### ISSUE TITLE
Reconsider use of listserve / e-mail lists throughout docs

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/docs#394]
As @ChrisMaddock points out in https://github.com/nunit/docs/pull/385#discussion_r439829242, the references to listserves and docs don't necessarily reflect current team process. 

Creating this issue here as a place to discuss and decide what we might want to do about that.

**Comment by CharliePoole** [comment]
@SeanKilleen There's something here that I've thought about in connection with other issues and didn't have the bandwidth to deal with, but I'll try in this case and let you see if it applies elsewhere as well.

Under our "new" (3 or 4 year old) organization, the various projects like the framework, engine, etc. are independent. Each has a lead and usually a team. Because there are few of us, some people are on multiple teams but the possibility that each team may want to do things differently remains.

I think it would be easy to waste a lot of time (including yours) in discussing some of this stuff unless we first decide things like "Are all projects required to have the same coding standard?" (using that page as an example) If the answer is yes, then keeping it in one place is a good idea. If the answer is no, ten we probably want to have a coding standard under each individual project that wants to adopt one - or maybe a reference to the "model" coding standard.

BTW, governance issues are just issues like any other, in the governance repo. So you too would be part of that discussion.

**Comment by SeanKilleen** [comment]
@CharliePoole great background, thanks! 

Suggested steps for different scenarios --

## Docs-initiated discussion

* Someone surfaces a discrepancy between docs & actual process and opens an issue, as @ChrisMaddock's comment triggered here.
* We tag it with `waiting:governance`
* We create a linked ticket in the governance repo. 
* As each ticket is resolved, the docs team has its path forward.

## Governance-initiated discussion

* Someone raises a governance question/issue such as your "are all projects required to have the same coding standard?" 
* A ticket is created in governance and discussed there.
* As that discussion is resolved, follow-up tickets may be created for the docs team to come up with a plan to implement the outcome of the discussion. A theoretical example: "We've decided that each project will have a different coding standard. Could you help us express that in the docs?" and the docs team (me at this point) might say "sure, how about copying the file across areas for now and then teams can submit PRs to iterate on them?"

This seems like it would be a decent workflow without too much overhead.

**Comment by CharliePoole** [comment]
Suggest you hold off on this for a while, until you get familiar with how we work.

Fact is, project decisions almost never get involved with the governance process because the governance rules basically say projects get to do what they want with only a few exceptions.

So how will you know the cases where a Core Team decision is needed? Well, because it's a small project you are almost always going to be in contact with a Core Team member who can tell you when something is needed and knows what to do to get it done. In this particular issue, and the related ones, you have had both me and @ChrisMaddock. Please let us help you!!!

I am afraid I got you started down this path by telling you more than was immediately useful to you, for which I apologize. Sorry for the information overload. :smiley:

**Comment by SeanKilleen** [comment]
@CharliePoole no worries at all! I appreciate you sending the info and correcting as I go. I'll probably hold off on anything not clearly scoped to docs until I fully understand the governance but your comments so far have been really helpful and are enabling me to continue to move forward. Thanks!
