### ISSUE TITLE
Communication Plan for Docfx Launch

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/docs#410]
Will generally include the bellow -- feedback / additions welcome!

* [x] Sean blog post about joining docs team (https://github.com/SeanKilleen/seankilleen.github.io/pull/476)
* [x] Write-up in README or Contributing guides (previously merged in docs site)
* [x] Tweets for the NUnit project members to send out (see below)
* [x] News entry on NUnit site (https://github.com/nunit/nunit.github.io/pull/82)
* [x] .NET Foundation Newsletter update (https://github.com/dotnet-foundation/website/pull/240)

We'll need to write up drafts of these things, ensure the core team feels OK about it since this will be my first major communication as a member of the project, etc.

**Comment by SeanKilleen** [comment]
@jnm2 took care of one of the above with https://github.com/dotnet-foundation/website/pull/240 (and I'm grateful! Thanks 😄 )

**Comment by SeanKilleen** [comment]
✅ News item PR added to https://github.com/nunit/nunit.github.io/pull/82

**Comment by SeanKilleen** [comment]
Potential tweet: 

> NUnit has a new docs site! Check out https://docs.nunit.org. We're looking for your contributions! https://github.com/nunit/docs

Figured we could keep it simple.

**Comment by SeanKilleen** [comment]
@CharliePoole @rprouse @jnm2 @ChrisMaddock @mikkelbu @OsirisTerje submitted for your FYI / feedback.

This would close out the communication plan for NUnit -- we can send the suggested tweet above from our accounts if we choose, publish the news announcement, my blog post will go live, etc.

I'm linking everything here -- particularly my blog post draft -- in case anyone would prefer me to say anything differently (feedback welcome!).

Once these things are out there, I'll close this issue, and we'll be firmly in post-launch, "crafting the long-term plan" phase of the docs project.

**Comment by ChrisMaddock** [comment]
All looks good to me. 😊

**Comment by CharliePoole** [comment]
This looks good to me.

It doesn't cover something I assumed fell under this, but maybe you are covering elsewhere: the internal docs update process, i.e. what kinds of things need whose approvals before merging. You've done a few implementation steps (e.g. owners of various areas) but you actually haven't said what reviews you want changes to have (if any before merging.

I would like it if that was explicitly stated, i.e. in a document of some kind rather than simply implied by the GitHub permissions, because some things may require giving more github access than is expected to be used. I think that's OK and even has some advantages because it allows people to step in and do more than they normally do in emergencies.

In my experience as a coach, I've always found it a positive thing for folks to have actually agreed to a review process and especially to have to exercise judgement rather than just going with whatever permission the software gives them. This is slightly contrarian in the wider world today, but not, I find, among the agile coaches with whom I hang out.

Of course, like Rob, I'm the equivalent of `root` on our GitHub projects, so this is probably on my mind more than for most people.

**Comment by SeanKilleen** [comment]
@CharliePoole yep, we've spoken about this and it will be covered as a separate item.

**Comment by jnm2** [comment]
@SeanKilleen Hey, sorry I missed this and didn't collaborate sooner. Is this the month that you'd like the news to go out, and is there any other emphasis you'd like to have in it?

**Comment by SeanKilleen** [comment]
@jnm2 no need to be sorry at all! You did exactly what I'd hoped and I appreciated not having to write it 😄 . Happy to have the announcement go out this month. And I think we're all good as long as nobody objects to the various content above

**Comment by SeanKilleen** [comment]
Alright, given that all these are out in the wild, I'm going to close this item, which officially also closes out the Docfx conversion project within GitHub! 

Next up, I'll move to the long-term roadmap and begin defining the vision / structure.
