### ISSUE TITLE
Cannot build docs on Linux

### ISSUE THREAD

**Issue by rprouse** [nunit/docs#533]
I attempted to work on our docs from a Linux machine but it failed to build.

1. Install Mono
2. Install Docfx
3. Clone this repo, cd into docs
4. Run `mono ~/bin/docfx.exe build`

The build fails with `System.TypeInitializationException: The type initializer for 'Microsoft.DocAsCode.Common.RelativePath'` with no useful information on where the bad relative path is.

My guess is that we have some Windows relative paths somewhere in an include or something like that? This isn't a serious issue, I'll switch to Windows to work on the docs, but I thought I'd document it in case I want to fix it.

**Comment by CharliePoole** [comment]
When I switched one to building one of my websites (using a different static generator) on Linux, I ran into all sorts of casing problems in paths. I think one gets lazy about that on Windows.

**Comment by SeanKilleen** [comment]
@rprouse @CharliePoole the docs are built in Linux as part of our every PR build process: https://github.com/nunit/docs/blob/master/.github/workflows/build-process.yml#L38

We use the GitHub Action container that is set up at https://github.com/nunit/docfx-action. The dockerfile can be found at https://github.com/nunit/docfx-action/blob/master/Dockerfile, and includes some additional steps/packages that are necessary. It pulls from the mono container, which also may be referencing some additional setup in order to get it working.

**Comment by rprouse** [comment]
If that is the case then probably an environmental error on my part. I'll try on a different machine or in a container.

**Comment by SeanKilleen** [comment]
@rprouse going to close this as I think there are multiple options for moving forward:

* [A Dockerfile defined in `nunit/docfx-action`](https://github.com/nunit/docfx-action/blob/master/Dockerfile) can build the docs
* GitHub Codespaces now works, which uses the Dockerfile at [`.devcontainer/Dockerfile`](https://github.com/nunit/docs/blob/master/.devcontainer/Dockerfile). It contains all the files to lint, spellcheck, serve the site, etc.

Let me know if you're still having trouble and I'm happy to work it out with you. 👍
