### ISSUE TITLE
OneTimeSetUp runs after code to generate TestCases

### ISSUE THREAD

**Issue by doubleyewdee** [nunit/docs#54]
Simple-ish example below. Basically setup for the fixture should probably run before test case values are generated. The below example throws a NullReferenceException before any tests are run which is not at all expected.

[TestFixture]
public class MyTests
{
    private static string SomeValue = null;
    private static IEnumerable<string> Values
    {
        get
        {
            yield return SomeValue.Substring(1) + "foo";
            yield return SomeValue.Substring(1) + "bar";
        }
    }

```
[OneTimeSetUp]
public void OneTimeSetUp()
{
    SomeValue = "some value";
}

[Test, TestCaseSource(nameof(Values))]
public void SomeTest(string value)
{
    Assert.IsNotNull(value);
}
```

}

**Comment by CharliePoole** [comment]
This is the documentation repository. You should file issues here if you see a problem with the documentation. This sounds more like a feature you want in NUnit itself. For that see https://github.com/nunit/nunit

In any case, what you describe here is well known and is how NUnit works. Tests are loaded (discovered, created) before being run. OneTimeSetUp is one of the first steps in __running__ the test, but it still takes place eons after the test is created. That's why you can't use things set in one time setup to create the tests.

You can think of it this way... until there is a test, it can't be run. Run depends on load. We can't have load depend on run as well or things would be circular. You might also think of a gui: what you see displayed in a gui __before running the tests__ is all the stuff that is defined at load time.

There is a feature, planned for some future release, called dynamic tests, which would not be loaded in advance but created on the fly at run time. You'll find that if you search the above repository. Sorry to say, there's no schedule for when we will do it, but it's on our horizon.

**Comment by doubleyewdee** [comment]
Thanks. My bad re destination (was looking in two places at once). Your explanation is clear, though I think the behavior remains rather unintuitive for a user not familiar with the internal logic of NUnit.

**Comment by CharliePoole** [comment]
Hmmm.... is my explanation is clear, maybe something like it should be in the docs... reopening...

**Comment by SeanKilleen** [comment]
🧹 Cleanup -- closing this issue because it's 3+ years old and I do not believe it's currently relevant (without hearing that many others have had similar confusion around it.)

Happy to reopen if anyone feels strongly about it. Thanks!
