### ISSUE TITLE
Linq in Standards

### ISSUE THREAD

**Issue by CharliePoole** [nunit/docs#58]
[Originally filed by @oznetmaster in the Dev repo]

Now that System.Linq is available in all build platforms, should there be anything in the coding standards about its use, and the format to be used when writing Linq lambda expressions?

**Comment by rprouse** [comment]
I am a bit uncomfortable putting too many standards around Linq beyond that they should be readable. For example, I tend to switch between the fluent syntax and the query syntax often, using whatever is clearest in the situation. Often I will write it one way and switch it to the other because I feel that it will be clearer.

I think it is pretty hard to codify that into a standard and we may even have differing opinions on what is more readable. Do we need a standard, or is it covered under "write clear, concise, readable code"?

**Comment by CharliePoole** [comment]
I tend to agree with you. I think @oznetmaster may have had something in mind in filing the original issue and I didn't want to just dump it at this point. However, if we **are** going to do anything, it would be good to have a proposal sooner rather than later.

One thing I miss from the Launchpad bug system was the ability to have issues "time out" if there was nothing being done on them.

**Comment by oznetmaster** [comment]
I was mostly interested in two things.

Making sure that developers were aware that Linq had been added to the 2.0 build so that it could be used in all builds of NUnit.

Possible adding something to the coding standards about how Linq should be formatted, as has been done with so many other syntactic issues.

**Comment by rprouse** [comment]
@oznetmaster do you have suggestions on the wording of the standards? That would give us something to discuss.

**Comment by SeanKilleen** [comment]
🧹 Cleanup -- closing this issue because it is 4+ years old and no longer appears relevant.

Feel free to ping if I'm getting that wrong and I'll be happy to reopen. 👍
