### ISSUE TITLE
Move release notes for the console/engine to the Console/Engine

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/docs#609]
The release notes for the console/engine is placed under the NUnit (framework) section, but should be placed under the Console/Engine section, which is also a high level section header.

![image](https://user-images.githubusercontent.com/203432/145887807-fe98b35e-9287-4e1d-91d7-d0d0a4852178.png)

**Comment by SeanKilleen** [comment]
@OsirisTerje I think it was placed where it was because that's where the original docs had it, and so that all the release notes would be in one spot from a links perspective, for those who may not be familiar with the different components.

But I agree that it's definitely absent. For now, I'll add it under the NUnit Engine section as well. PR shortly on that.

**Comment by OsirisTerje** [comment]
@SeanKilleen I believe that may have been so way back in time, but now we have many more components, e.g. the adapter release notes are not in the NUnit section, but in their own.
