### ISSUE TITLE
update current year in footer

### ISSUE THREAD

**Issue by Arhell** [nunit/docs#620]
![21-12-2021 20-37-32](https://user-images.githubusercontent.com/26163841/146981470-7cd67222-e2b0-4e82-90eb-5ea8685c9510.jpg)
cc @SeanKilleen 
js?
in the DocFX documentation, I unfortunately did not find how to do it differently

**Comment by SeanKilleen** [comment]
@Arhell I'd say this is a lower priority and I'd be happy to update the hard-coded value. 

But yes, if we want to tackle this, JS would probably be the best way given Docfx's current constraints.

The current hard-coded value is found in `footer.tmpl.partial`.

**Comment by OsirisTerje** [comment]
That year should **not** be updated.  It is the year of First Publication, and thus has to stay that way.   However, since the site is constantly evolving, one *can* add a range to it, so that it reads  2018 - 2021.  That is the format we use for the adapter.  If one choose not to use  a range, which one can, then the first date of publication should be used, thus 2018.

**Comment by Arhell** [comment]
> That year should **not** be updated. It is the year of First Publication, and thus has to stay that way. However, since the site is constantly evolving, one _can_ add a range to it, so that it reads 2018 - 2021. That is the format we use for the adapter. If one choose not to use a range, which one can, then the first date of publication should be used, thus 2018. See e.g. [copyrightlaws.com](https://www.copyrightlaws.com/copyright-symbol-notice-year/)

Got it, thanks, I will do 2018-current
