### ISSUE TITLE
Missing parenthesis and curly bracket on the Ignore attribute page

### ISSUE THREAD

**Issue by MichalMoudry** [nunit/docs#765]
Ignore attribute page has a missing parenthesis in Ignore Until code example.
- **ref**: [Ignore Attribute - Ignore Until section](https://docs.nunit.org/articles/nunit/writing-tests/attributes/ignore.html#ignore-until "Link to Ignore attribute documentation page")
- **additional info**: parenthesis is missing after Until parameter of the Ignore attribute

Code example in Test Syntax section has a missing curly bracket.
- class _SuccessTests_ does not have a closing curly bracket

I have a fix for these issues ([Branch - comparison](https://github.com/nunit/docs/compare/master...MichalMoudry:nunit-docs:master)). Should I open a PR?

Also, I have noticed that lines in code examples have incorrect (as per [C# Coding Conventions - Layout conventions](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#layout-conventions "Test")) and inconsistent indentation. Is that intentional or it should be fixed as well?

**Comment by OsirisTerje** [comment]
Raise a PR. 

I believe @SeanKilleen is in the process of moving code snippets into the docs/snippets and referencing from there, but these errors can just be fixed in the meanwhile.  Having the code snippets in the snippets solution means they're compiled and checked too.  But it will take time, so raise the PR :-)

**Comment by SeanKilleen** [comment]
@MichalMoudry PRs always welcome! ♥️
