### ISSUE TITLE
Add linting for line lengths and update docs format

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/docs#830]
The software I use for docs hasn't been affected by this for a long time and it has almost never bothered me so I've just chosen "one long line" for the docs for a long time.

@manfred-brands raised this as a DX issue. I'm totally open to doing this and to suggestions on what the line length should be.

**Comment by stevenaw** [comment]
Some thoughts without a hard suggestion:

Some tools in the JS ecosystem have a default line length of 80. Personally, I feel like that's too short - at least for code - unless we want to support editing from within a console window. My own Visual Studio setup on a single-screen laptop right now tends to show around 120 characters with the TestExplorer and SolutionExplorer widgets open on the left and right respectively.

**Comment by SeanKilleen** [comment]
@manfred-brands any objection to starting with 120?

**Comment by manfred-brands** [comment]
> @manfred-brands any objection to starting with 120?

None

**Comment by OsirisTerje** [comment]
This is not working.
I just pushed up the latest framework release notes changes and got blown out of the sky due to the line-length restriction now in place.  Sorry, but it doesn't make sense to me.  The line length counter counts seems to count all characters, also those included in links.  Look at this:   

![image](https://github.com/nunit/docs/assets/203432/e532c733-1cf7-4213-98d9-775f32b31797)

Which ends up like this:

![image](https://github.com/nunit/docs/assets/203432/a0e00d05-5289-4bb6-95a5-346049f31a04)

Which to me looks very nice. 

And the line length checker complains like this:

![image](https://github.com/nunit/docs/assets/203432/5271fa06-5ab5-4373-8556-277533535a7f)

So, I suggest this change is reverted.

**Comment by SeanKilleen** [comment]
* I believe we excluded release notes from these changes. So we can exclude this file as well.
* There are several tools which provide automated support for this within IDEs that we can make use of. I'll do my best to help with this and to point out how to do it.

I suggest that it's a good idea for most of the docs and that we can ignore it easily enough when needed.
