### ISSUE TITLE
NUnit runner(?) 3.4.1 issue with test runners

### ISSUE THREAD

**Issue by leadensky** [nunit/docs#92]
I recently updated NUnit (plus NUnit.Runner et al) from 3.0.1 to 3.4.1. I use NCrunch in my development and after the update, many of my tests stopped appearing in NCrunch, and in the DevExpress test runner. In talking with NCrunch support, they were able to find this error:

System.Exception: Unable to resolve underlying type for NUnit fixture: Tests.Common.SimpleSUTBase`1
at nCrunch.Module.NUnit3.Integration.NUnit3DiscoveryListener.resolveClassMethod(String className, String methodName)
at nCrunch.Module.NUnit3.Integration.NUnit3DiscoveryListener.discoverTests(XDocument discoveryData)
at nCrunch.Module.NUnit3.Integration.NUnit3DiscoveryListener.RaiseCallbackEvent(String eventArgument)

The DevExpress test runner turned up a different error:

System.MissingMethodException
Method not found: 'NUnit.Framework.Interfaces.ITest NUnit.Framework.Api,NUnitTestAssemblyRunner.Load(System.Reflection.Assembly, System.Collections.IDictionary)'.

After rolling my test projects back to 3.0.1, all the tests appeared and ran correctly. In subsequent testing, I was able to update NUnit and NUnit.Runner to 3.2.1 successfully.

**Comment by CharliePoole** [comment]
@leadensky It's useful for us to know about the problems with these third-party runners, so thanks for telling us. Nevertheless... I'm closing this issue for several reasons.

First, trivially, it's not a documentation issue, and this is the documentation repository.

Second, even if we moved it to the nunit repository, it's not really a bug for us, at least with the info available. WRT third-party runners, our communication is pretty much one-way. We try to tell them how to use NUnit, but we don't actually know how they use it in their code. It's probably best if the authors of those runners create issues to tell us what broke for them in 3.4.1. If it's an actual API that they are using, we will fix it. Sometimes, third parties will go for the convenience of some non-API Type or method, which we can change from release to release. If that's the case, we probably wouldn't fix it.
 
In the case of NCrunch, the stack trace doesn't include any of our code. Based on the method name, they are trying to resolve some class and method name inside the test assembly. NUnit has no official API to do that, so they may have gone the route of doing their own reflection. I can't be sure. Please encourage them to let us know.

For DevExpress, it seems clear that they are relying on an interface, which we consider internal. It's publicly exposed because custom attributes use it, but such attributes have to be recompiled for every new release of NUnit. AFAIK, they have not been in communication with us and are not on our mailing list for third-party runner authors. We'd be glad to talk to them, of course.
