### ISSUE TITLE
Nuint 3 Test Adapter Not Work in VS2015 properly?

### ISSUE THREAD

**Issue by DreamExpress** [nunit/docs#95]
Nuint 3 Test Adapter Ver3.4.0 is setup  in my visual studio 2015,but when I use the menu ( Test | Windows | Test Explorer ) to show Unit Test Explorer, the Test Explorer Show nothing.

Is it a bug of Nuint 3 Test Adapter?Not support visual studio 2015 properly?
![default](https://cloud.githubusercontent.com/assets/20766967/17318501/7076768a-58b9-11e6-9024-bb315790bcbf.PNG)

The correct snap picture should be like this,as blow:
![image](https://cloud.githubusercontent.com/assets/20766967/17318640/4ffb00dc-58ba-11e6-90bd-f50948099eb4.png)

**Comment by rprouse** [comment]
This is a known issue with the latest KB update to Visual Studio 2015 Update 3. I think it is caused by incourrect resource assemblies and only affects non-english versions.

See https://connect.microsoft.com/VisualStudio/feedbackdetail/view/2979953/uni-tests-disappeared-after-updating-visual-studio-2015-update3-kb for instructions on fixing.

Download from the following link, https://1drv.ms/u/s!Ah2_fRsQIuFtgQUZChN8vYBWUfu9

To unblock from this issue. Please follow the following steps.

1.    Download the attachment ResourcePack.zip and unzip it.
2.    Close the Visual Studio if it’s open.
3.    Take a backup of the existing resource DLL (Microsoft.VisualStudio.TestWindow.Core.resources.dll) in `<ProgramFilesx86>\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\<Lang>`
4.    Copy the new resource DLL (Microsoft.VisualStudio.TestWindow.Core.resources.dll) from the unzip location `ResourcePack\<Lang>` to `<ProgramFilesx86>\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\`

**Comment by DreamExpress** [comment]
Thank you very much!The issue now is unblock.
